### ISSUE TITLE
Master-slave only for Sharding-Proxy execute `SHOW TABLES` occur exception

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1006]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?

3.0.0.M2.SNAPSHOT

### Expected behavior

Master-slave only for Sharding-Proxy execute `SHOW TABLES`, return correct result.

### Actual behavior

Error message on mysql command line: 

```
ERROR: 
 table
```

Exception on Sharding-Proxy:

```
[ERROR] 17:02:39.600 [nioEventLoopGroup-5-2] i.s.p.b.common.ExecuteBackendHandler - ExecuteBackendHandler
java.lang.NullPointerException: null
	at io.shardingsphere.core.merger.dal.show.ShowTablesMergedResult.init(ShowTablesMergedResult.java:75) ~[classes/:na]
	at io.shardingsphere.core.merger.dal.show.ShowTablesMergedResult.<init>(ShowTablesMergedResult.java:64) ~[classes/:na]
	at io.shardingsphere.core.merger.dal.DALMergeEngine.merge(DALMergeEngine.java:61) ~[classes/:na]
	at io.shardingsphere.proxy.backend.common.ExecuteBackendHandler.mergeDQLorDAL(ExecuteBackendHandler.java:204) ~[classes/:na]
	at io.shardingsphere.proxy.backend.common.ExecuteBackendHandler.merge(ExecuteBackendHandler.java:180) ~[classes/:na]
	at io.shardingsphere.proxy.backend.common.ExecuteBackendHandler.doExecuteInternal(ExecuteBackendHandler.java:127) ~[classes/:na]
	at io.shardingsphere.proxy.backend.common.ExecuteBackendHandler.execute(ExecuteBackendHandler.java:106) ~[classes/:na]
	at io.shardingsphere.proxy.transport.mysql.packet.command.text.query.ComQueryPacket.execute(ComQueryPacket.java:104) [classes/:na]
	at io.shardingsphere.proxy.frontend.mysql.MySQLFrontendHandler$1.run(MySQLFrontendHandler.java:96) [classes/:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.16.Final.jar:4.1.16.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

```

**Comment by tristaZero** [comment]
fixed it.
