### ISSUE TITLE
sharding-jdbc&druid exception:Communications link failure

### ISSUE THREAD

**Issue by guanxiaochen** [sharding-sphere/sharding-sphere#1040]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?
sharding-jdbc-2.0.0 and sharding-jdbc-3.0.0.M1 

### Expected behavior

druid:
```
<property name="validationQuery" value="select 1" />
<property name="initialSize" value="1" />
<property name="maxActive" value="100" />
<property name="minIdle" value="1" />
<property name="maxWait" value="30000" />
<property name="testOnBorrow" value="false" />
<property name="testOnReturn" value="false" />
<property name="testWhileIdle" value="true" />
<property name="timeBetweenEvictionRunsMillis" value="30000" />
<property name="minEvictableIdleTimeMillis" value="240000" />
<property name="removeAbandoned" value="true" />
<property name="removeAbandonedTimeout" value="1800" />
<property name="logAbandoned" value="true" />
```
mysql server conf:
```
interactive_timeout:300
wait_timeout:300
```

### Actual behavior

```
java.sql.SQLException: connection holder is null
	at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1107)
	at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1100)
	at com.alibaba.druid.pool.DruidPooledConnection.commit(DruidPooledConnection.java:712)
	at io.shardingsphere.core.jdbc.adapter.AbstractConnectionAdapter.commit(AbstractConnectionAdapter.java:96)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:272)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:757)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:726)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:521)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at com.huitongjy.tasksystem.process.WorkProcess$$EnhancerBySpringCGLIB$$495d60fd.saveAnswer(<generated>)
	at com.huitongjy.tasksystem.facade.impl.WorkService.saveTaskAnswer(WorkService.java:158)
	at com.huitongjy.tasksystem.facade.impl.WorkService$$FastClassBySpringCGLIB$$2a6bc02c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.huitongjy.tasksystem.support.aop.InterfaceAop.handleViewConfig(InterfaceAop.java:71)
	at sun.reflect.GeneratedMethodAccessor224.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at com.huitongjy.tasksystem.facade.impl.WorkService$$EnhancerBySpringCGLIB$$4f82cc5b.saveTaskAnswer(<generated>)
	at com.alibaba.dubbo.common.bytecode.Wrapper20.invokeMethod(Wrapper20.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 703,187 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3427)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3327)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
	at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4846)
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:553)
	at com.alibaba.druid.filter.FilterAdapter.connection_setAutoCommit(FilterAdapter.java:984)
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:549)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.setAutoCommit(ConnectionProxyImpl.java:430)
	at com.alibaba.druid.pool.DruidPooledConnection.setAutoCommit(DruidPooledConnection.java:681)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.shardingsphere.core.jdbc.adapter.invocation.JdbcMethodInvocation.invoke(JdbcMethodInvocation.java:48)
	at io.shardingsphere.core.jdbc.adapter.WrapperAdapter.replayMethodsInvocation(WrapperAdapter.java:74)
	at io.shardingsphere.core.jdbc.adapter.AbstractConnectionAdapter.getConnection(AbstractConnectionAdapter.java:67)
	at io.shardingsphere.core.jdbc.core.connection.ShardingConnection.getMetaData(ShardingConnection.java:67)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getNextResultSet(DefaultResultSetHandler.java:197)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:154)
	at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.huitongjy.common.mvc.mybatis.PageMybatisInterceptor.intercept(PageMybatisInterceptor.java:56)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:60)
	at com.sun.proxy.$Proxy83.handleResultSets(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:60)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:73)
	at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
	at com.sun.proxy.$Proxy84.query(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:60)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)
	at sun.reflect.GeneratedMethodAccessor166.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.huitongjy.tasksystem.dao.support.sharding.MybatisShardingInterceptor.intercept(MybatisShardingInterceptor.java:38)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:60)
	at com.sun.proxy.$Proxy82.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:66)
	at sun.reflect.GeneratedMethodAccessor230.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:358)
	at com.sun.proxy.$Proxy27.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:163)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:68)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy51.selectByPrimaryKey(Unknown Source)
	at com.huitongjy.tasksystem.dao.dataprovider.task.TaskInfoProvider.findTaskInfoByPrimaryKey(TaskInfoProvider.java:239)
	at com.huitongjy.tasksystem.dao.dataprovider.task.TaskInfoProvider$$FastClassBySpringCGLIB$$674f2bf4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at com.huitongjy.tasksystem.dao.support.sharding.DBShardingInterceptor.invoke(DBShardingInterceptor.java:37)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at com.huitongjy.tasksystem.dao.dataprovider.task.TaskInfoProvider$$EnhancerBySpringCGLIB$$42bee4dd.findTaskInfoByPrimaryKey(<generated>)
	at com.huitongjy.tasksystem.handler.TaskHandler.findTaskInfoMoById(TaskHandler.java:594)
	at com.huitongjy.tasksystem.handler.TaskHandler.taskIsOverdue(TaskHandler.java:1367)
	at com.huitongjy.tasksystem.validator.WorkRequestValidator.validateTaskIsOverdue(WorkRequestValidator.java:270)
	at com.huitongjy.tasksystem.validator.WorkRequestValidator.validateUserTaskAnswer(WorkRequestValidator.java:77)
	at com.huitongjy.tasksystem.process.WorkProcess.saveAnswer(WorkProcess.java:553)
	at com.huitongjy.tasksystem.process.WorkProcess$$FastClassBySpringCGLIB$$6fdbdbe1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	... 50 common frames omitted
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2914)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3337)
	... 131 common frames omitted

```

### Reason analyze
The following is my guess:

Does the sharding-jdbc refer to the connection, and the connection pool is returned to the actual unused pool, and the connection pool will record the last use time when returned, so that the idle time of the server records is not consistent with the idle time of the connection pool records, causing the actual idle time to exceed the threshold value, when the connection is obtained and the free connection is detected regularly, Because the last use time recorded in the connection pool did not exceed the configuration time, it was not properly released.

英文不好,中文再写一遍,个人猜测,有待验证:
是不是sharding-jdbc引用到了连接,实际未使用就归还了连接池,归还的时候连接池会记录最后使用时间,这样服务器记录的空闲时间和连接池记录的空闲时间不一致,造成实际空闲时间超过了阈值,获取连接和定时检测空闲连接的时候,因为没有连接池里记录的最后使用时间没有超过配置时间,所以没有正确释放.
没有找到有效的验证方法和解决方案,希望帮忙分析一下

### Please provide the reproduce example codes (such as a github link).

```
<property name="validationQuery" value="select 1" />
<property name="initialSize" value="1" />
<property name="maxActive" value="100" />
<property name="minIdle" value="1" />
<property name="maxWait" value="30000" />
<property name="testOnBorrow" value="false" />
<property name="testOnReturn" value="false" />
<property name="testWhileIdle" value="true" />
<property name="timeBetweenEvictionRunsMillis" value="30000" />
<property name="minEvictableIdleTimeMillis" value="240000" />
<property name="removeAbandoned" value="true" />
<property name="removeAbandonedTimeout" value="1800" />
<property name="logAbandoned" value="true" />
```

**Comment by ma-xiao-guang-64** [comment]
Thank you for your issue, but it is not ss bug, please add maxEvictableIdleTimeMillis to druid config

**Comment by guanxiaochen** [comment]
Still can't
```
		<property name="keepAlive" value="true" />
		<property name="timeBetweenEvictionRunsMillis" value="60000" />
		<property name="minEvictableIdleTimeMillis" value="180000" />
		<property name="maxEvictableIdleTimeMillis" value="300000" />
```

**Comment by guanxiaochen** [comment]
正常来说只要配置了testWhileIdle=true和timeBetweenEvictionRunsMillis= 60000
就会每次获取连接的时候查询一下当前连接的空闲时间是多少，如果超过60000毫秒就会执行validationQuery校验
minEvictableIdleTimeMillis 和 maxEvictableIdleTimeMillis 每隔60000毫秒定时校验的时使用，也就是即使之前没有配置maxEvictableIdleTimeMillis，也不应该出现这种问题的。。只是不会自动从连接池里释放罢了，但是获取的时候还是会剔除这种连接的。

**Comment by guanxiaochen** [comment]
补充一下，上边猜测，mybatis默认启用了localcache，同一事务下相同查询会走缓存，也就是获取statement后并没有执行数据库查询，正常来说应该没有问题，但是使用sharding-jdbc后，事务内一开始查询走的从库，接下来如果有DML和DDL操作，之后的相同查询获取的是主库数据源，就可能出现这次获取了连接但是未使用而取缓存的问题，我配置的是一主一从

**Comment by guanxiaochen** [comment]
上边的猜测补充一下，mybatis默认启用了localcache，走缓存时，也就是获取statement后并没有执行数据库查询，MasterSlavePreparedStatement构造器会获取数据库连接

**Comment by koala775** [comment]
Do you have resloved? I also have this problem.

**Comment by 2012110325** [comment]
@terrymanu @maxiaoguang64  麻烦咨询下 这个问题有处理没?    程序里配置了 testWhileIdle   timeBetweenEvictionRunsMillis 其它普通的mybatis执行都没有问题.  只有引入shardingjdbc的库有 这种问题:  The last packet successfully received from the server was xxxxx milliseconds ago.            sharding-jdbc-core 3.0.0.
链接池druid 有这条日志:     testWhileIdle true, idle millis 89, minIdle 1, poolingCount 1, timeBetweenEvictionRunsMillis 60000, lastValidIdleMillis 89, driver com.mysql.jdbc.Driver,      是sharding-jdbc 会直接设置connection的活跃时间而不实际去探活么?

**Comment by chenqi14** [comment]
找到原因了吗，我最近也遇到了，很迷 @guanxiaochen
