### ISSUE TITLE
sql exception

### ISSUE THREAD

**Issue by dawe001** [sharding-sphere/sharding-sphere#1089]
SELECT count(0) FROM sys_privilege_user A INNER JOIN sys_privilege_user_role B ON B.user_id = A.id LEFT JOIN sys_privilege_role C ON B.role_id = C.id AND C.level != 1
The above sql throw exception : Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.NullPointerException。
But it will be OK when take out ！ like this: SELECT count(0) FROM sys_privilege_user A INNER JOIN sys_privilege_user_role B ON B.user_id = A.id LEFT JOIN sys_privilege_role C ON B.role_id = C.id AND C.level = 1

 

### Which version of Sharding-Sphere do you using?
3.0.0.M1

### Expected behavior
work OK

### Actual behavior
 throw exception : Caused by: org.apache.ibatis.exceptions.PersistenceException: 
 Error querying database.  Cause: java.lang.NullPointerException。

**Comment by dawe001** [comment]
Steps to reproduce the behavior:
select count(0) from tableA xx join tableB on xxxxxxx and B.xx != xx 
The problem seems with ！ when use join

**Comment by ma-xiao-guang-64** [comment]
@dawe001 please provider exception stack

**Comment by dawe001** [comment]
@ma-xiao-guang-64  
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: java.lang.NullPointerException
### The error may exist in com/yqm/manager/system/dao/self/SysSelectDicDao.java (best guess)
### The error may involve com.yqm.manager.system.dao.self.SysSelectDicDao.getSysDic-Inline
### The error occurred while setting parameters
### SQL: select count(0) from (select A.id,A.name,A.description,A.c_key 'key' from sys_select_dic A left JOIN sys_privilege_role C ON A.id=C.id AND C.level!=0  where A.type=? ORDER BY A.priority) tmp_count
### Cause: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 71 more
Caused by: java.lang.NullPointerException
	at io.shardingsphere.core.jdbc.metadata.dialect.JDBCShardingRefreshHandler.execute(JDBCShardingRefreshHandler.java:49)
	at io.shardingsphere.core.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:159)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.github.pagehelper.SqlUtil.doProcessPage(SqlUtil.java:478)
	at com.github.pagehelper.SqlUtil._processPage(SqlUtil.java:407)
	at com.github.pagehelper.SqlUtil.processPage(SqlUtil.java:374)
	at com.github.pagehelper.PageHelper.intercept(PageHelper.java:255)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy248.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 77 more

**Comment by ma-xiao-guang-64** [comment]
@dawe001 OK, like this [878](https://github.com/sharding-sphere/sharding-sphere/issues/878)
please use 3.0.0.M2

**Comment by dawe001** [comment]
@ma-xiao-guang-64  
sorry，i can't find 3.0.0.M2 。the last version is 3.0.0.M1 ??

**Comment by ma-xiao-guang-64** [comment]
@dawe001  download master code and package it

**Comment by ma-xiao-guang-64** [comment]
@dawe001 in 3.0.0.M1 i can not reappear, please give me a demo

**Comment by ma-xiao-guang-64** [comment]
@dawe001  in after on can not support !=
  ```
      if (lexerEngine.skipIfEqual(DefaultKeyword.ON)) {//keyword on
            do {
                basicExpressionParser.parse(sqlStatement);
                lexerEngine.accept(Symbol.EQ);//only support equal
                basicExpressionParser.parse(sqlStatement);
            } while (lexerEngine.skipIfEqual(DefaultKeyword.AND));
        } else if (lexerEngine.skipIfEqual(DefaultKeyword.USING)) {
            lexerEngine.skipParentheses(sqlStatement);
        }
```

**Comment by dawe001** [comment]
@ma-xiao-guang-64 
 Will later versions support other Symbol like ！ ??

**Comment by ma-xiao-guang-64** [comment]
@dawe001 There is no plan at the moment

**Comment by terrymanu** [comment]
use `!=` join table does make sense.
