### ISSUE TITLE
java.lang.RuntimeException: Driver com.mysql.jdbc.Driver claims to not accept jdbcUrl,

### ISSUE THREAD

**Issue by guoming** [sharding-sphere/sharding-sphere#1093]
dataSources: 
  ds_master: 
    url: jdbc:sqlserver://10.2.29.234:1433;databasename=TestDB_Shard1
    username: sa
    password: xxxx
    
  ds_slave0: 
    url: jdbc:sqlserver://10.2.21.216:1433;databasename=TestDB_Shard1
    username: sa
    password: xxxx

masterSlaveRule:
  name: ds_ms
  masterDataSourceName: ds_master
  slaveDataSourceNames: 
    - ds_slave0

root@DESKTOP-PACCV9P:/sharding-proxy# tree
.
├── bin
│   ├── start.bat
│   ├── start.sh
│   └── stop.sh
├── conf
│   ├── config.yaml
│   └── logback.xml
├── lib
│   ├── commons-lang3-3.6.jar
│   ├── groovy-2.4.5-indy.jar
│   ├── guava-18.0.jar
│   ├── HikariCP-java7-2.4.11.jar
│   ├── logback-classic-1.1.2.jar
│   ├── logback-core-1.1.2.jar
│   ├── mysql-connector-java-5.1.30.jar
│   ├── netty-all-4.1.16.Final.jar
│   ├── sharding-core-3.0.0.M1.jar
│   ├── sharding-proxy-3.0.0.M1.jar
│   ├── slf4j-api-1.7.7.jar
│   ├── snakeyaml-1.16.jar
│   └── **sqljdbc42.jar**
└── logs
    └── stdout.log

**Comment by guoming** [comment]
@terrymanu 
https://github.com/guoming/sharding-proxy-DEMO

**Comment by zzzhangjian** [comment]
多数据源是，spring boot 2.0以上版本
数据库配置：url 改为 jdbc-url
例如：
ds_slave0:
jdbc-url: jdbc:sqlserver://10.2.21.216:1433;databasename=TestDB_Shard1
username: sa
password: xxxx

**Comment by terrymanu** [comment]
@zzzhangjian Hello, only english can use to discuss issue.

**Comment by guoming** [comment]
@zzzhangjian 
Exception in thread "main" java.lang.ExceptionInInitializerError
        at io.shardingsphere.proxy.Bootstrap.initializeRuleRegistry(Bootstrap.java:55)
        at io.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:39)
Caused by: Cannot create property=dataSources for JavaBean=io.shardingsphere.core.yaml.proxy.YamlProxyConfiguration@4c98385c
 in 'reader', line 57, column 1:
    dataSources:
    ^
Cannot create property=jdbc-url for JavaBean=io.shardingsphere.core.yaml.sharding.DataSourceParameter@4cdf35a9
 in 'reader', line 59, column 5:
        jdbc-url: jdbc:sqlserver://10.2. ...
        ^
Unable to find property 'jdbc-url' on class: io.shardingsphere.core.yaml.sharding.DataSourceParameter
 in 'reader', line 59, column 15:
        jdbc-url: jdbc:sqlserver://10.2.29.234:143 ...
                  ^

 in 'reader', line 58, column 3:
      ds_master:
      ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:345)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:410)
        at io.shardingsphere.core.yaml.proxy.YamlProxyConfiguration.unmarshal(YamlProxyConfiguration.java:71)
        at io.shardingsphere.proxy.config.RuleRegistry.<init>(RuleRegistry.java:69)
        at io.shardingsphere.proxy.config.RuleRegistry.<clinit>(RuleRegistry.java:52)
        ... 2 more
Caused by: Cannot create property=jdbc-url for JavaBean=io.shardingsphere.core.yaml.sharding.DataSourceParameter@4cdf35a9
 in 'reader', line 59, column 5:
        jdbc-url: jdbc:sqlserver://10.2. ...
        ^
Unable to find property 'jdbc-url' on class: io.shardingsphere.core.yaml.sharding.DataSourceParameter
 in 'reader', line 59, column 15:
        jdbc-url: jdbc:sqlserver://10.2.29.234:143 ...
                  ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373)
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:170)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:297)
        ... 12 more
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'jdbc-url' on class: io.shardingsphere.core.yaml.sharding.DataSourceParameter
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:322)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)

**Comment by tuohai666** [comment]
Sharding-Proxy didn't support SQLServer yet.
