### ISSUE TITLE
3.0.0.M2 TransactionListener throw NullPointerException

### ISSUE THREAD

**Issue by Pramy** [sharding-sphere/sharding-sphere#1116]
- environment
java 1.8.144
3.0.0.M2
- question
An exception occurs when inserting data in batches
```
Exception thrown by subscriber method listen(io.shardingsphere.core.transaction.event.TransactionEvent) on subscriber io.shardingsphere.core.transaction.listener.TransactionListener@50265207 when dispatching event: io.shardingsphere.core.transaction.event.WeakXaTransactionEvent@54be0a09
java.lang.NullPointerException: null
	at io.shardingsphere.core.transaction.listener.TransactionListener.listen(TransactionListener.java:61) ~[sharding-core-3.0.0.M2.jar:?]
	at sun.reflect.GeneratedMethodAccessor140.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87) ~[guava-24.0-jre.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72) ~[guava-24.0-jre.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398) ~[guava-24.0-jre.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67) ~[guava-24.0-jre.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108) ~[guava-24.0-jre.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:212) ~[guava-24.0-jre.jar:?]
	at io.shardingsphere.core.jdbc.adapter.AbstractConnectionAdapter.setAutoCommit(AbstractConnectionAdapter.java:91) ~[sharding-jdbc-3.0.0.M2.jar:?]
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCleanupAfterCompletion(DataSourceTransactionManager.java:374) ~[spring-jdbc-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.cleanupAfterCompletion(AbstractPlatformTransactionManager.java:1007) ~[spring-tx-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:793) ~[spring-tx-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714) ~[spring-tx-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:532) ~[spring-tx-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:304) ~[spring-tx-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at 
```
But there is no problem with using 3.0.0.M2-SNAPSHOT

**Comment by terrymanu** [comment]
could you fill necessary information follow in issue template？

For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?

### Which project do you using? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze

### Steps to reproduce the behavior

### For bug report, please *MUST* provide the reproduce example codes (such as a github link).

**Comment by wangjinyu1994** [comment]
Have you solved this problem?I also encountered this problem after upgrading to the latest version

**Comment by wslongchen** [comment]
I ncountered this problem after upgrading to the latest version ,too

**Comment by niuniu9631** [comment]
hello,when will the next release plan be released? @terrymanu 
there is a repair plan for the current version（3.0.0.M2）.

**Comment by joey168** [comment]
@terrymanu When is 3.0.0M3 pushed to Maven warehouse? thanks

**Comment by terrymanu** [comment]
It is already on the way. Sync to maven centre repo need 1-2 days generally.

**Comment by joey168** [comment]
ok,thank you for the answer!
