### ISSUE TITLE
3.0.0M2 已经指定了数据库，但是却报在其他库下找不到表的错误

### ISSUE THREAD

**Issue by fengxiaotx** [sharding-sphere/sharding-sphere#1121]
版本3.0.0M2  已经指定了数据库，但是却报在其他库下找不到表的错误，请问一下，这个是我配置有问题，还是bug
用的是
        <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>3.0.0.M2</version>
        </dependency>

配置如下
sharding.jdbc.datasource.names=ds

sharding.jdbc.datasource.ds.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds.driver-class-name=com.mysql.cj.jdbc.Driver
sharding.jdbc.datasource.ds.url=jdbc:mysql://XXX:3306/fz_ssp_school?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
sharding.jdbc.datasource.ds.username=fss
sharding.jdbc.datasource.ds.password=8U@JjXc9@4KiVw@N

sharding.jdbc.config.sharding.tables.org_clzss_student_subject_rel.actual-data-nodes=ds.org_clzss_student_subject_rel_$->{0..15}
sharding.jdbc.config.sharding.tables.org_clzss_student_subject_rel.table-strategy.inline.sharding-column=school_id
sharding.jdbc.config.sharding.tables.org_clzss_student_subject_rel.table-strategy.inline.algorithm-expression=org_clzss_student_subject_rel_$->{school_id % 16}
sharding.jdbc.config.sharding.tables.org_clzss_student_subject_rel.key-generator-column-name=id

启动报错如下
Caused by: java.sql.SQLSyntaxErrorException: Table 'fz_ssp_account.org_clzss_student_subject_rel_0' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1422)
	at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3182)
	at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3170)
	at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:50)
	at com.mysql.cj.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3223)
	at io.shardingsphere.core.metadata.table.executor.TableMetaDataLoader.getPrimaryKeys(TableMetaDataLoader.java:106)
	at io.shardingsphere.core.metadata.table.executor.TableMetaDataLoader.getColumnMetaDataList(TableMetaDataLoader.java:93)
	at io.shardingsphere.core.metadata.table.executor.TableMetaDataLoader.load(TableMetaDataLoader.java:82)
	at io.shardingsphere.core.metadata.table.executor.TableMetaDataLoader.load(TableMetaDataLoader.java:75)
	at io.shardingsphere.core.metadata.table.executor.TableMetaDataLoader.access$000(TableMetaDataLoader.java:49)
	at io.shardingsphere.core.metadata.table.executor.TableMetaDataLoader$1.call(TableMetaDataLoader.java:121)
	at io.shardingsphere.core.metadata.table.executor.TableMetaDataLoader$1.call(TableMetaDataLoader.java:117)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by terrymanu** [comment]
Hello, only english can use to discuss issue.
