### ISSUE TITLE
sharding-jdbc  3.0.0.M2 启动报事物异常

### ISSUE THREAD

**Issue by wangjinyu1994** [sharding-sphere/sharding-sphere#1122]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### For bug report, please *MUST* provide the reproduce example codes (such as a github link).
sharding-jdbc     3.0.0.M2
spring配置
从M1升级到M2以后启动项目会出现一个关于事物的异常

`八月 09, 2018 3:31:06 下午 com.google.common.eventbus.EventBus dispatch
严重: Could not dispatch event: io.shardingsphere.core.transaction.event.WeakXaTransactionEvent@41a399e3 to handler [wrapper public void io.shardingsphere.core.transaction.listener.TransactionListener.listen(io.shardingsphere.core.transaction.event.TransactionEvent) throws java.sql.SQLException]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at io.shardingsphere.core.jdbc.adapter.AbstractConnectionAdapter.setAutoCommit(AbstractConnectionAdapter.java:91)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:225)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:427)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at com.alibaba.druid.support.spring.stat.DruidStatInterceptor.invoke(DruidStatInterceptor.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.jiurun.iot.util.aop.MethodTimeAdvice.invoke(MethodTimeAdvice.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)`

at com.jiurun.iot.service.impl.DeviceLogServiceImpl$$EnhancerBySpringCGLIB$$53769fcd.updateCreateIfNotExistsTable(<generated>)
	at com.jiurun.iot.data.runnable.util.pool.CreateTable.run(CreateTable.java:21)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at io.shardingsphere.core.transaction.listener.TransactionListener.listen(TransactionListener.java:61)
	... 33 more

**Comment by terrymanu** [comment]
Hello, only english can use to discuss issue.
