### ISSUE TITLE
When you get the configuration from reg center,How is the registry configured?Where are the relevant documents?

### ISSUE THREAD

**Issue by siusn** [sharding-sphere/sharding-sphere#1164]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?

3.0.0.M2

### Which project do you using? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC

**Comment by terrymanu** [comment]
http://shardingsphere.io/document/current/en/manual/sharding-jdbc/usage/orchestration/

**Comment by siusn** [comment]
Unable to load the configuration, how should zk node be configured

**Comment by siusn** [comment]
Unable to load the configuration, how should zk node be configured?

2018-08-20 19:01:05.690  WARN  --- [           main] [o.s.c.s.ClassPathXmlApplicationContext       :550] : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [META-INF/orche/zookeeper/cloud/shardingTables.xml]: Cannot resolve reference to bean 'shardingDataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingDataSource': Invocation of init method failed; nested exception is io.shardingsphere.core.exception.ShardingConfigurationException: No available sharding rule configuration to load.
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [META-INF/orche/zookeeper/cloud/shardingTables.xml]: Cannot resolve reference to bean 'shardingDataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingDataSource': Invocation of init method failed; nested exception is io.shardingsphere.core.exception.ShardingConfigurationException: No available sharding rule configuration to load.
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1531)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1276)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1081)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:856)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at io.shardingsphere.example.spring.namespace.jpa.main.orche.zookeeper.ShardingOnlyWithTables.main(ShardingOnlyWithTables.java:29)

**Comment by siusn** [comment]
I made a mistake. Thank you
