### ISSUE TITLE
proxy is support mysql 8 ？

### ISSUE THREAD

**Issue by zhengjieyuan** [sharding-sphere/sharding-sphere#1228]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?
3.0.0.M2
### Which project do you using? Sharding-JDBC or Sharding-Proxy?
Sharding-Proxy
### Expected behavior
Support mysql 8 ？
### Actual behavior

my config.yaml:

ds_0:
   driverClassName: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://192.168.1.100:3306/dyyt?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC

and add mysql-connector-java-8.0.11.jar to sharding-proxy-3.0.0.M2/lib
### Reason analyze
start proxy logs:

Unable to find property 'driverClassName' on class: io.shardingsphere.core.rule.DataSourceParameter
 in 'reader', line 13, column 21:
       driverClassName: com.mysql.cj.jdbc.Driver
                        ^
 in 'reader', line 12, column 2:
     ds_0: 
     ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:312)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:345)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:410)
	at io.shardingsphere.proxy.Bootstrap.loadLocalConfiguration(Bootstrap.java:76)
	at io.shardingsphere.proxy.Bootstrap.main(Bootstrap.java:62)

**Comment by zhengjieyuan** [comment]
it work.but print 
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary. 
for logs

I remove mysql-connector-java-5.1.30.jar  and config.yml set 

`dataSources:
 ds_0:
   url: jdbc:mysql://192.168.100.100:3306/dyyt_0?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
   username: root
   password: 123456
   autoCommit: true
   connectionTimeout: 30000
   idleTimeout: 60000
   maxLifetime: 1800000
   maximumPoolSize: 10
 ds_1:
   url: jdbc:mysql://192.168.100.231:3307/dyyt_1?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
   username: root
   password: 123456
   autoCommit: true
   connectionTimeout: 30000
   idleTimeout: 60000
   maxLifetime: 1800000
   maximumPoolSize: 10`
