### ISSUE TITLE
use sharding-sphere after throw TransactionListener NullPointerException

### ISSUE THREAD

**Issue by joey168** [sharding-sphere/sharding-sphere#1233]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere do you using?
3.0.0.M2

### Which project do you using? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Expected behavior
The query is normal, but every time an exception is thrown
Is it compatible with previous versions of Hibernate?
I switch from 1.5.x,my software on 1.5.x Normal work
Please help analyze the problem, thank you!!
no thorw by: Exception thrown by subscriber method listen(io.shardingsphere.core.transaction.event.TransactionEvent)
### Actual behavior
every time an exception is thrown
Exception thrown by subscriber method listen(io.shardingsphere.core.transaction.event.TransactionEvent)
java.lang.NullPointerException
	at io.shardingsphere.core.transaction.listener.TransactionListener.listen(TransactionListener.java:64)
### Reason analyze
Is it compatible with previous versions of Hibernate or spring?
my software use a base class to get session lock following code
public Session getSession() {
        if(sessionFactory != null && sessionFactory.getCurrentSession() != null) {
            return sessionFactory.getCurrentSession();
        } else {
            return session;
        }
    }
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc

my configuration:

<bean id="preciseDateDatabaseShardingAlgorithm" class="com.dayi35.core.spot.common.sharding.algorithm.SingleKeyDatabaseDatePreciseShardingAlgorithm" />
    <bean id="rangeDateDatabaseShardingAlgorithm" class="com.dayi35.core.spot.common.sharding.algorithm.SingleKeyDatabaseDateRangeShardingAlgorithm" />
    <sharding:standard-strategy id="databaseShardingStrategy" sharding-column="create_date" precise-algorithm-ref="preciseDateDatabaseShardingAlgorithm" range-algorithm-ref="rangeDateDatabaseShardingAlgorithm"/>
    
    <bean id="preciseDateTableShardingAlgorithm" class="com.dayi35.core.spot.common.sharding.algorithm.SingleKeyTableDatePreciseShardingAlgorithm" />
    <bean id="rangeDateTableShardingAlgorithm" class="com.dayi35.core.spot.common.sharding.algorithm.SingleKeyTableDateRangeShardingAlgorithm" />
    <sharding:standard-strategy id="tableShardingStrategy" sharding-column="create_date" precise-algorithm-ref="preciseDateTableShardingAlgorithm" range-algorithm-ref="rangeDateTableShardingAlgorithm"/>
    
    <bean id="generateKeyAlgorithm" class="com.dayi35.core.spot.common.sharding.keygen.DefaultKeyGenerator"></bean>
    
    <sharding:data-source id="shardingDataSource" registry-center-ref="regCenter" overwrite="true">
        
        <sharding:sharding-rule data-source-names="dataSource,ds-2017" default-data-source-name="dataSource">
            
            <sharding:table-rules>
                <sharding:table-rule logic-table="finance_account_log" database-strategy-ref="databaseShardingStrategy" table-strategy-ref="tableShardingStrategy" />
                
            </sharding:table-rules>
        </sharding:sharding-rule>
        <sharding:props>
            <prop key="sql.show">true</prop>
        </sharding:props>
    </sharding:data-source>

    
    <bean id="strategySessionFactory" class="org.springframework.orm.hibernate4.LocalSessionFactoryBean">
        <property name="dataSource" ref="shardingDataSource" />
        <property name="packagesToScan" value="com.dayi35.core.model,com.dayi35.core.spot.**,com.dayi35.core.finance.**.model,com.dayi35.payment.factory.model,com.dayi35.payment.bank.pingan.core.model,com.dayi35.core.sys.system.model" />
        <property name="hibernateProperties">
            <props>
                <prop key="hibernate.dialect">org.hibernate.dialect.MySQLDialect</prop>
                <prop key="hibernate.show_sql">false</prop>
                <prop key="hibernate.hbm2ddl.auto">false</prop>
                <prop key="hibernate.current_session_context_class">org.springframework.orm.hibernate4.SpringSessionContext</prop>
                
                <prop key="hibernate.cache.use_second_level_cache">false</prop>
                <prop key="hibernate.cache.use_query_cache">false</prop>
                <prop key="hibernate.cache.use_structured_entries">false</prop>
                <prop key="hibernate.enable_lazy_load_no_trans">true</prop>
                <prop key="hibernate.bytecode.use_reflection_optimizer">false</prop>
            </props>
        </property>
        
        <property name="namingStrategy"><ref bean="namingStrategy"/></property>
    </bean>

    
    <bean id="shardingTransactionManager" class="org.springframework.orm.hibernate4.HibernateTransactionManager">
        <property name="sessionFactory" ref="strategySessionFactory" />
    </bean>

### For bug report, please *MUST* provide the reproduce example codes (such as a github link).
20180905 14:11:08.206[INFO][qtp2111700021-20] - Sharding-Sphere-SQL.log : Rule Type: sharding
20180905 14:11:08.206[INFO][qtp2111700021-20] - Sharding-Sphere-SQL.log : Logic SQL: select count(*) as y0_ from finance_account_log this_ where this_.pay_type in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) and this_.pay_uc_id=? and this_.status=? and this_.create_date between ? and ?
20180905 14:11:08.207[INFO][qtp2111700021-20] - Sharding-Sphere-SQL.log : SQLStatement: SelectStatement(super=DQLStatement(super=AbstractSQLStatement(type=DQL, tables=Tables(tables=[Table(name=finance_account_log, alias=Optional.of(this_))]), conditions=Conditions(orCondition=OrCondition(andConditions=[AndCondition(conditions=[Condition(column=Column(name=create_date, tableName=finance_account_log), operator=BETWEEN, positionValueMap={}, positionIndexMap={0=28, 1=29})])])), sqlTokens=[TableToken(beginPosition=28, skippedSchemaNameLength=0, originalLiterals=finance_account_log)], parametersIndex=30)), containStar=false, selectListLastPosition=23, groupByLastPosition=0, items=[AggregationSelectItem(type=COUNT, innerExpression=(*), alias=Optional.of(y0_), derivedAggregationSelectItems=[], index=-1)], groupByItems=[], orderByItems=[], limit=null, subQueryStatement=null)
20180905 14:11:08.208[INFO][qtp2111700021-20] - Sharding-Sphere-SQL.log : Actual SQL: dataSource ::: select count(*) as y0_ from finance_account_log_8 this_ where this_.pay_type in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) and this_.pay_uc_id=? and this_.status=? and this_.create_date between ? and ? ::: [[1, -9, -114, -112, -115, -100, -101, -109, -102, -117, -107, -116, -118, 103, 104, 108, -103, 105, 106, 107, -8, -120, 109, -999, -121, -41, 20135177197638921, 1, 2018-08-06 00:00:00.992, 2018-09-05 23:59:59.992]]
20180905 14:11:08.243[INFO][qtp2111700021-20] - Sharding-Sphere-SQL.log : Rule Type: sharding
20180905 14:11:08.243[INFO][qtp2111700021-20] - Sharding-Sphere-SQL.log : Logic SQL: select this_.id as y0_ from finance_account_log this_ where this_.pay_type in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) and this_.pay_uc_id=? and this_.status=? and this_.create_date between ? and ? order by this_.ser_id desc limit ?
20180905 14:11:08.244[INFO][qtp2111700021-20] - Sharding-Sphere-SQL.log : SQLStatement: SelectStatement(super=DQLStatement(super=AbstractSQLStatement(type=DQL, tables=Tables(tables=[Table(name=finance_account_log, alias=Optional.of(this_))]), conditions=Conditions(orCondition=OrCondition(andConditions=[AndCondition(conditions=[Condition(column=Column(name=create_date, tableName=finance_account_log), operator=BETWEEN, positionValueMap={}, positionIndexMap={0=28, 1=29})])])), sqlTokens=[TableToken(beginPosition=28, skippedSchemaNameLength=0, originalLiterals=finance_account_log), ItemsToken(beginPosition=23, isFirstOfItemsSpecial=false, items=[this_.ser_id AS ORDER_BY_DERIVED_0 ])], parametersIndex=31)), containStar=false, selectListLastPosition=23, groupByLastPosition=0, items=[CommonSelectItem(expression=this_.id, alias=Optional.of(y0_))], groupByItems=[], orderByItems=[OrderItem(owner=Optional.of(this_), name=Optional.of(ser_id), orderDirection=DESC, nullOrderDirection=ASC, index=-1, alias=Optional.of(ORDER_BY_DERIVED_0))], limit=null, subQueryStatement=null)
20180905 14:11:08.244[INFO][qtp2111700021-20] - Sharding-Sphere-SQL.log : Actual SQL: dataSource ::: select this_.id as y0_ , this_.ser_id AS ORDER_BY_DERIVED_0 from finance_account_log_8 this_ where this_.pay_type in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) and this_.pay_uc_id=? and this_.status=? and this_.create_date between ? and ? order by this_.ser_id desc limit ? ::: [[1, -9, -114, -112, -115, -100, -101, -109, -102, -117, -107, -116, -118, 103, 104, 108, -103, 105, 106, 107, -8, -120, 109, -999, -121, -41, 20135177197638921, 1, 2018-08-06 00:00:00.992, 2018-09-05 23:59:59.992, 10]]
20180905 14:11:08.255[INFO][qtp2111700021-20] - Sharding-Sphere-SQL.log : Rule Type: sharding
20180905 14:11:08.255[INFO][qtp2111700021-20] - Sharding-Sphere-SQL.log : Logic SQL: select this_.id as id1_80_0_, this_.create_date as create_d2_80_0_, this_.modify_date as modify_d3_80_0_, this_.account_type as account_4_80_0_, this_.accrual as accrual5_80_0_, this_.agent_org_id as agent_or6_80_0_, this_.balance as balance7_80_0_, this_.bussniss_type as bussniss8_80_0_, this_.cargo_hand_num as cargo_ha9_80_0_, this_.cargo_interest as cargo_i10_80_0_, this_.cargo_interest_puchas as cargo_i11_80_0_, this_.error_type as error_t12_80_0_, this_.finish_method as finish_13_80_0_, this_.frozen as frozen14_80_0_, this_.full_fund as full_fu15_80_0_, this_.in_out_type as in_out_16_80_0_, this_.interest as interes17_80_0_, this_.link_person as link_pe18_80_0_, this_.mobile as mobile19_80_0_, this_.name as name20_80_0_, this_.out_frozen as out_fro21_80_0_, this_.pay_type as pay_typ22_80_0_, this_.pay_uc_id as pay_uc_23_80_0_, this_.product_type as product24_80_0_, this_.product_type_str as product25_80_0_, this_.protocol_number as protoco26_80_0_, this_.receive_uc_account_type as receive27_80_0_, this_.receive_uc_id as receive28_80_0_, this_.relation_ser_id as relatio29_80_0_, this_.remark as remark30_80_0_, this_.ser_id as ser_id31_80_0_, this_.short_fund as short_f32_80_0_, this_.spe_business as spe_bus33_80_0_, this_.status as status34_80_0_, this_.sys_business as sys_bus35_80_0_, this_.total_in_cash as total_i36_80_0_, this_.total_out_cash as total_o37_80_0_, this_.userable as userabl38_80_0_, this_.version as version39_80_0_ from finance_account_log this_ where this_.pay_type in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) and this_.pay_uc_id=? and this_.status=? and this_.create_date between ? and ? and this_.id in (?) order by this_.ser_id desc
20180905 14:11:08.255[INFO][qtp2111700021-20] - Sharding-Sphere-SQL.log : SQLStatement: SelectStatement(super=DQLStatement(super=AbstractSQLStatement(type=DQL, tables=Tables(tables=[Table(name=finance_account_log, alias=Optional.of(this_))]), conditions=Conditions(orCondition=OrCondition(andConditions=[AndCondition(conditions=[Condition(column=Column(name=create_date, tableName=finance_account_log), operator=BETWEEN, positionValueMap={}, positionIndexMap={0=28, 1=29})])])), sqlTokens=[TableToken(beginPosition=1465, skippedSchemaNameLength=0, originalLiterals=finance_account_log)], parametersIndex=31)), containStar=false, selectListLastPosition=1460, groupByLastPosition=0, items=[CommonSelectItem(expression=this_.frozen, alias=Optional.of(frozen14_80_0_)), CommonSelectItem(expression=this_.receive_uc_account_type, alias=Optional.of(receive27_80_0_)), CommonSelectItem(expression=this_.product_type_str, alias=Optional.of(product25_80_0_)), CommonSelectItem(expression=this_.modify_date, alias=Optional.of(modify_d3_80_0_)), CommonSelectItem(expression=this_.remark, alias=Optional.of(remark30_80_0_)), CommonSelectItem(expression=this_.name, alias=Optional.of(name20_80_0_)), CommonSelectItem(expression=this_.status, alias=Optional.of(status34_80_0_)), CommonSelectItem(expression=this_.version, alias=Optional.of(version39_80_0_)), CommonSelectItem(expression=this_.balance, alias=Optional.of(balance7_80_0_)), CommonSelectItem(expression=this_.cargo_hand_num, alias=Optional.of(cargo_ha9_80_0_)), CommonSelectItem(expression=this_.short_fund, alias=Optional.of(short_f32_80_0_)), CommonSelectItem(expression=this_.id, alias=Optional.of(id1_80_0_)), CommonSelectItem(expression=this_.error_type, alias=Optional.of(error_t12_80_0_)), CommonSelectItem(expression=this_.finish_method, alias=Optional.of(finish_13_80_0_)), CommonSelectItem(expression=this_.link_person, alias=Optional.of(link_pe18_80_0_)), CommonSelectItem(expression=this_.accrual, alias=Optional.of(accrual5_80_0_)), CommonSelectItem(expression=this_.relation_ser_id, alias=Optional.of(relatio29_80_0_)), CommonSelectItem(expression=this_.mobile, alias=Optional.of(mobile19_80_0_)), CommonSelectItem(expression=this_.cargo_interest, alias=Optional.of(cargo_i10_80_0_)), CommonSelectItem(expression=this_.account_type, alias=Optional.of(account_4_80_0_)), CommonSelectItem(expression=this_.agent_org_id, alias=Optional.of(agent_or6_80_0_)), CommonSelectItem(expression=this_.receive_uc_id, alias=Optional.of(receive28_80_0_)), CommonSelectItem(expression=this_.spe_business, alias=Optional.of(spe_bus33_80_0_)), CommonSelectItem(expression=this_.total_in_cash, alias=Optional.of(total_i36_80_0_)), CommonSelectItem(expression=this_.cargo_interest_puchas, alias=Optional.of(cargo_i11_80_0_)), CommonSelectItem(expression=this_.pay_uc_id, alias=Optional.of(pay_uc_23_80_0_)), CommonSelectItem(expression=this_.ser_id, alias=Optional.of(ser_id31_80_0_)), CommonSelectItem(expression=this_.pay_type, alias=Optional.of(pay_typ22_80_0_)), CommonSelectItem(expression=this_.total_out_cash, alias=Optional.of(total_o37_80_0_)), CommonSelectItem(expression=this_.in_out_type, alias=Optional.of(in_out_16_80_0_)), CommonSelectItem(expression=this_.full_fund, alias=Optional.of(full_fu15_80_0_)), CommonSelectItem(expression=this_.interest, alias=Optional.of(interes17_80_0_)), CommonSelectItem(expression=this_.out_frozen, alias=Optional.of(out_fro21_80_0_)), CommonSelectItem(expression=this_.userable, alias=Optional.of(userabl38_80_0_)), CommonSelectItem(expression=this_.bussniss_type, alias=Optional.of(bussniss8_80_0_)), CommonSelectItem(expression=this_.product_type, alias=Optional.of(product24_80_0_)), CommonSelectItem(expression=this_.sys_business, alias=Optional.of(sys_bus35_80_0_)), CommonSelectItem(expression=this_.create_date, alias=Optional.of(create_d2_80_0_)), CommonSelectItem(expression=this_.protocol_number, alias=Optional.of(protoco26_80_0_))], groupByItems=[], orderByItems=[OrderItem(owner=Optional.of(this_), name=Optional.of(ser_id), orderDirection=DESC, nullOrderDirection=ASC, index=-1, alias=Optional.of(ser_id31_80_0_))], limit=null, subQueryStatement=null)
20180905 14:11:08.258[INFO][qtp2111700021-20] - Sharding-Sphere-SQL.log : Actual SQL: dataSource ::: select this_.id as id1_80_0_, this_.create_date as create_d2_80_0_, this_.modify_date as modify_d3_80_0_, this_.account_type as account_4_80_0_, this_.accrual as accrual5_80_0_, this_.agent_org_id as agent_or6_80_0_, this_.balance as balance7_80_0_, this_.bussniss_type as bussniss8_80_0_, this_.cargo_hand_num as cargo_ha9_80_0_, this_.cargo_interest as cargo_i10_80_0_, this_.cargo_interest_puchas as cargo_i11_80_0_, this_.error_type as error_t12_80_0_, this_.finish_method as finish_13_80_0_, this_.frozen as frozen14_80_0_, this_.full_fund as full_fu15_80_0_, this_.in_out_type as in_out_16_80_0_, this_.interest as interes17_80_0_, this_.link_person as link_pe18_80_0_, this_.mobile as mobile19_80_0_, this_.name as name20_80_0_, this_.out_frozen as out_fro21_80_0_, this_.pay_type as pay_typ22_80_0_, this_.pay_uc_id as pay_uc_23_80_0_, this_.product_type as product24_80_0_, this_.product_type_str as product25_80_0_, this_.protocol_number as protoco26_80_0_, this_.receive_uc_account_type as receive27_80_0_, this_.receive_uc_id as receive28_80_0_, this_.relation_ser_id as relatio29_80_0_, this_.remark as remark30_80_0_, this_.ser_id as ser_id31_80_0_, this_.short_fund as short_f32_80_0_, this_.spe_business as spe_bus33_80_0_, this_.status as status34_80_0_, this_.sys_business as sys_bus35_80_0_, this_.total_in_cash as total_i36_80_0_, this_.total_out_cash as total_o37_80_0_, this_.userable as userabl38_80_0_, this_.version as version39_80_0_ from finance_account_log_8 this_ where this_.pay_type in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) and this_.pay_uc_id=? and this_.status=? and this_.create_date between ? and ? and this_.id in (?) order by this_.ser_id desc ::: [[1, -9, -114, -112, -115, -100, -101, -109, -102, -117, -107, -116, -118, 103, 104, 108, -103, 105, 106, 107, -8, -120, 109, -999, -121, -41, 20135177197638921, 1, 2018-08-06 00:00:00.992, 2018-09-05 23:59:59.992, 1]]
九月 05, 2018 2:11:08 下午 com.google.common.eventbus.EventBus$LoggingHandler handleException
严重: Exception thrown by subscriber method listen(io.shardingsphere.core.transaction.event.TransactionEvent) on subscriber io.shardingsphere.core.transaction.listener.TransactionListener@3f00cd13 when dispatching event: io.shardingsphere.core.transaction.event.WeakXaTransactionEvent@7290d4fe
java.lang.NullPointerException
	at io.shardingsphere.core.transaction.listener.TransactionListener.listen(TransactionListener.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:95)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:80)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:76)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:119)
	at com.google.common.eventbus.EventBus.post(EventBus.java:215)
	at io.shardingsphere.core.jdbc.adapter.AbstractConnectionAdapter.commit(AbstractConnectionAdapter.java:96)
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doCommit(JdbcTransaction.java:112)
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:180)
	at org.springframework.orm.hibernate4.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:584)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:518)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:292)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at net.bull.javamelody.MonitoringSpringInterceptor.invoke(MonitoringSpringInterceptor.java:73)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.dayi35.core.finance.account.service.impl.AccountLogServiceImpl$$EnhancerBySpringCGLIB$$51b4a3e9.searchAccountLogBySysBusiness(<generated>)
	at com.dayi35.controller.finance.pcV2.per.PcV2PerAccountController.getLogList(PcV2PerAccountController.java:508)
	at com.dayi35.controller.finance.pcV2.per.PcV2PerAccountController.tradeLog(PcV2PerAccountController.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:201)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:178)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.dayi35.core.spot.common.filter.XssFilter.doFilter(XssFilter.java:57)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at com.dayi35.core.spot.common.filter.EmojiFilter.doFilter(EmojiFilter.java:23)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:744)

**Comment by terrymanu** [comment]
duplicate with #1116

**Comment by joey168** [comment]
thank you!!
