### ISSUE TITLE
sharing-sphere doesn't work with skywalking 

### ISSUE THREAD

**Issue by CatteRio** [sharding-sphere/sharding-sphere#1254]
For English only, other languages we will close it directly.

Please answer these questions before submitting your issue. Thanks!

Before submit a new issue, please check existed issue first, to make sure your issue is not a duplicated one.

### Which version of Sharding-Sphere do you using?
3.0.0.M3
### Which project do you using? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC 
### Expected behavior
skywalking monitor the performance of sharding-sphere
### Actual behavior
**skywalking auto agent plugin couldn't  collect data,so I read the source code of agent plugin,I found that the class name it hooked was sharding-jdbc 1.5.x version.Then I used the opentracing api to load skywalking agent.when I restarted the application,collector server console print many null point Exception like the folllow text, I'm wondering if the versions of skywalking and sharding-sphere aren't match,but I have tried many tests,so can you give me some advices of how to make the Skywalking work with sharding-sphere or a demo case for me . thanks very much** 
Sep 12, 2018 1:31:44 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@5f8a026
java.lang.NullPointerException
	at org.apache.skywalking.apm.collector.configuration.service.ComponentLibraryCatalogService.getComponentId(ComponentLibraryCatalogService.java:50)
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.standardization.SpanIdExchanger.exchange(SpanIdExchanger.java:62)
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.preBuild(SegmentParse.java:116)
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.parser.SegmentParse.parse(SegmentParse.java:68)
	at org.apache.skywalking.apm.collector.analysis.segment.parser.provider.service.SegmentParseService.parse(SegmentParseService.java:42)
	at org.apache.skywalking.apm.collector.agent.grpc.provider.handler.TraceSegmentServiceHandler$1.onNext(TraceSegmentServiceHandler.java:48)
	at org.apache.skywalking.apm.collector.agent.grpc.provider.handler.TraceSegmentServiceHandler$1.onNext(TraceSegmentServiceHandler.java:45)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:252)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:629)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by terrymanu** [comment]
We are not implement yet, becuase 3.0.0 is not released.
You can use sharding-opentracing now.
We will do it after 3.0.0 released

**Comment by CatteRio** [comment]
> We are not implement yet, becuase 3.0.0 is not released.
> You can use sharding-opentracing now.
> We will do it after 3.0.0 released

But I still get into trouble with opentracing . could you please tell me which version of skywalking that you suggest to match the sharding-sphere 3.0.0.M3 opentracing

**Comment by tuohai666** [comment]
@CatteRio 
**could you please tell me which version of skywalking that you suggest to match the sharding-sphere 3.0.0.M3 opentracing**
it's 5.0.5

You could get the guide here:
http://shardingsphere.io/document/current/cn/features/orchestration/apm/

**Comment by tuohai666** [comment]
@CatteRio 
1. SkyWalking auto agent plugin will available in 6.0.0.
2. 3.0.0.M3 will not be supported any longer, please turn to 3.0.0 release with SkyWalking 5.0.0-GA.

I think this question is clear and should be closed.
