### ISSUE TITLE
why not use sql:SELECT * FROM table1 WHERE id IN (SELECT id FROM table2) 

### ISSUE THREAD

**Issue by zhanyao** [sharding-sphere/sharding-sphere#1259]
### Which version of Sharding-Sphere do you using?
3.0.0.M3
### Which project do you using? Sharding-JDBC or Sharding-Proxy?
 Sharding-JDBC
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc
2018-09-14 09:29:59.559 ERROR - [http-nio-8080-exec-6] c.x.f.api.config.BiExceptionHandler      : F00504999
com.xinwis.framework.exception.BiException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'IDENTIFIER', literals is 'c'.
	at com.xinwis.dubbo.filter.BiExceptionFilter.invoke(BiExceptionFilter.java:96) ~[framework-dubbo-2.2.1-20180731.100948-1.jar:na]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:103) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:172) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:80) ~[dubbo-2.6.2.jar:2.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_172]
2018-09-14 09:29:59.560 ERROR - [http-nio-8080-exec-6] c.x.f.api.config.BiExceptionHandler      : {"exceptionMsg":"系统错误","debugMsg":"msg:nested exception is org.apache.ibatis.exceptions.PersistenceException: \r\n### Error querying database.  Cause: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'IDENTIFIER', literals is 'c'.\r\n### The error may exist in xinwis/finance/dao/MaterialMapper.xml\r\n### The error may involve xinwis.finance.dao.MaterialMapper.selectByMaterialIds-Inline\r\n### The error occurred while setting parameters\r\n### SQL: select                ID, CODE, NAME, TYPE, FEE_AREA, PROPERTY_STATUS, INDUSTRY_STATE, PROJ_ID, DEPARTMENT_ID,     CREATE_TIME, UPDATE_TIME, CREATE_EMPLOYE_ID, UPDATE_EMPLOYE_ID, IS_DEL, DATA_SOURCE,      BIZ_ID, FEE_DAY, OWNER_IDS, OWNER_NAMES, OWNER_PHONES,TENANT_IDS, TENANT_NAMES, TENANT_PHONES, EXIST_ACCOUNT, BANK_ID, ACCOUNT_NAME,     ACCOUNT_NUMBER, PERIODS_ID, BUILDING_ID, SEAT_ID, FLOOR_ID, PARKING_ID, PARKINGAREA_ID         from fin_material m     where m.PROJ_ID = ? AND IS_DEL = ?             AND m.ID IN (SELECT c.MATERIAL_ID FROM fin_material_customer c       WHERE c.CUSTOMER_ID IN       (SELECT mc.CUSTOMER_ID FROM fin_material_customer mc WHERE mc.MATERIAL_ID = ? AND mc.TYPE  <>  7)       AND c.TYPE  <>  7       )\r\n### Cause: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'IDENTIFIER', literals is 'c'.stackTrace:BiException{errorCode='999', errorMsg='系统错误', serviceName='null', serviceMethodName='null', serviceDebugMsg='nested exception is org.apache.ibatis.exceptions.PersistenceException: \r\n### Error querying database.  Cause: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'IDENTIFIER', literals is 'c'.\r\n### The error may exist in xinwis/finance/dao/MaterialMapper.xml\r\n### The error may involve xinwis.finance.dao.MaterialMapper.selectByMaterialIds-Inline\r\n### The error occurred while setting parameters\r\n### SQL: select                ID, CODE, NAME, TYPE, FEE_AREA, PROPERTY_STATUS, INDUSTRY_STATE, PROJ_ID, DEPARTMENT_ID,     CREATE_TIME, UPDATE_TIME, CREATE_EMPLOYE_ID, UPDATE_EMPLOYE_ID, IS_DEL, DATA_SOURCE,      BIZ_ID, FEE_DAY, OWNER_IDS, OWNER_NAMES, OWNER_PHONES,TENANT_IDS, TENANT_NAMES, TENANT_PHONES, EXIST_ACCOUNT, BANK_ID, ACCOUNT_NAME,     ACCOUNT_NUMBER, PERIODS_ID, BUILDING_ID, SEAT_ID, FLOOR_ID, PARKING_ID, PARKINGAREA_ID         from fin_material m     where m.PROJ_ID = ? AND IS_DEL = ?             AND m.ID IN (SELECT c.MATERIAL_ID FROM fin_material_customer c       WHERE c.CUSTOMER_ID IN       (SELECT mc.CUSTOMER_ID FROM fin_material_customer mc WHERE mc.MATERIAL_ID = ? AND mc.TYPE  <>  7)       AND c.TYPE  <>  7       )\r\n### Cause: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'RIGHT_PAREN', actual token is 'IDENTIFIER', literals is 'c'.'}\r\n\tat com.xinwis.dubbo.filter.BiExceptionFilter.invoke(BiExceptionFilter.java:96)\r\n\tat com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)\r\n\tat com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:103)\r\n\tat com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)\r\n\tat com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:172)\r\n\tat com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)\r\n\tat com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:80)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\n","bizContent":"","exceptionCode":"F00504999"}

**Comment by terrymanu** [comment]
hello, please read document before you submit issue, we don't support this SQL, just reference: http://shardingsphere.io/document/current/en/features/sharding/usage-standard/sql/
