### ISSUE TITLE
NullPointerException: cause by uppercase SQL

### ISSUE THREAD

**Issue by serendin** [sharding-sphere/sharding-sphere#1295]
### Which version of Sharding-Sphere did you use?
3.0.0.M3
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC
### Actual behavior
Error Cause by:
```
java.lang.NullPointerException: Cannot invoke method mod() on null object
    at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91) 
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48) 
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) 
    at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35) 
    …...
    at io.shardingsphere.core.routing.strategy.inline.InlineShardingStrategy.execute(InlineShardingStrategy.java:86)
    at io.shardingsphere.core.routing.strategy.inline.InlineShardingStrategy.doSharding(InlineShardingStrategy.java:68)
    at io.shardingsphere.core.routing.strategy.inline.InlineShardingStrategy.doSharding(InlineShardingStrategy.java:59) 
    at io.shardingsphere.core.routing.strategy.inline.InlineShardingStrategy.execute(InlineShardingStrategy.java:86) 
    at io.shardingsphere.core.routing.type.standard.StandardRoutingEngine.routeTables(StandardRoutingEngine.java:147) 
    at io.shardingsphere.core.routing.type.standard.StandardRoutingEngine.route(StandardRoutingEngine.java:97) 
    at io.shardingsphere.core.routing.type.standard.StandardRoutingEngine.route(StandardRoutingEngine.java:82)
    at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.route(ParsingSQLRouter.java:140)
    at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.route(ParsingSQLRouter.java:99)
    at io.shardingsphere.core.routing.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:66) 
    at io.shardingsphere.core.jdbc.core.statement.ShardingPreparedStatement.sqlRoute(ShardingPreparedStatement.java:245) 
    at io.shardingsphere.core.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:188) 
```
### Reason analyze

This exception happened when sql statement was written in uppercase form. Sharding-JDBC can’t identify the field and get the object when run the algorithm expression . 
As we know, sql statement is not case sensitive. It would be great If Sharding-JDBC was also not case sensitive.

**Comment by terrymanu** [comment]
SQL is case sensitive or case insensitive use can config by database server. So we don't want case insensitive at any scenario. 
Case sensitive is best practice
