### ISSUE TITLE
JPA config may trigger MySQLSyntaxErrorException

### ISSUE THREAD

**Issue by olderzhou** [sharding-sphere/sharding-sphere#1321]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere did you use?
3.0.0.M4
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
 Sharding-JDBC
### Expected behavior
normal launch
### Actual behavior
raise MySQLSyntaxErrorException
### Reason analyze (If you can)
only diffrence is ddl-auto value， when set to create,none everything fine, when comes to update or validate , it raise MySQLSyntaxErrorException, my point is the default datasource table config not equals to others core datasource tables config, and they use the same tables config validate rule.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlString(AbstractSchemaMigrator.java:559)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlStrings(AbstractSchemaMigrator.java:504)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.createTable(AbstractSchemaMigrator.java:277)
	at org.hibernate.tool.schema.internal.GroupedSchemaMigratorImpl.performTablesMigration(GroupedSchemaMigratorImpl.java:71)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.performMigration(AbstractSchemaMigrator.java:207)
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:114)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:183)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:72)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:312)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:892)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:57)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1758)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1089)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:859)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265)
	at com.klaus.mikaelson.sharekafka.ShareKafkaApplication.main(ShareKafkaApplication.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 't_emp' already exists

### Example codes for reproduce this issue (such as a github link).
https://github.com/olderzhou/share-kafka.git

**Comment by terrymanu** [comment]
What's mean for `Table 't_emp' already exists`?
is t_emp your own table?

**Comment by olderzhou** [comment]
i got 3 datasource , default has tables t_emp,
ds-0 ; order, order_item
ds-1 ; order, order_item

and i set ddl-auto to create, then i run application, everything's fine, then i change ddl-auto to validate, now , i got exception says Table 't_emp' already exists

**Comment by olderzhou** [comment]
sharding:
  jdbc:
    datasource:
      names: ds-master-0,ds-master-1,ds-master-0-slave-0,ds-master-0-slave-1,ds-master-1-slave-0,ds-master-1-slave-1,ds-default
      ds-master-0:
        type: com.zaxxer.hikari.HikariDataSource    
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_master_0?useSSL=false
        username: root
        password: 123456
        max-active: 3
      ds-master-0-slave-0:
        type: com.zaxxer.hikari.HikariDataSource    
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_master_0_slave_0?useSSL=false
        username: root
        password: 123456
        max-active: 3
      ds-master-0-slave-1:
        type: com.zaxxer.hikari.HikariDataSource    
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_master_0_slave_1?useSSL=false
        username: root
        password: 123456
        max-active: 3
      ds-master-1:
        type: com.zaxxer.hikari.HikariDataSource    
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_master_1?useSSL=false
        username: root
        password: 123456
        max-active: 3
      ds-master-1-slave-0:
        type: com.zaxxer.hikari.HikariDataSource    
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_master_1_slave_0?useSSL=false
        username: root
        password: 123456
        max-active: 3
      ds-master-1-slave-1:
        type: com.zaxxer.hikari.HikariDataSource    
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_master_1_slave_1?useSSL=false
        username: root
        password: 123456
        max-active: 3
      #系统默认独立数据源
      ds-default:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: 123456
        minimum-idle: 1
        maximum-pool-size: 30
        auto-commit: true
        idle-timeout: 60000
        max-lifetime: 1800000
        connection-timeout: 60000
    config:
      sharding:
        default-data-source-name: ds-default
#        default-key-generator-class-name: io.shardingsphere.core.keygen.DefaultKeyGenerator
        default-database-strategy:
          inline:
            sharding-column: user_id
            algorithm-expression: ds-$->{user_id % 2}
        binding-tables: 
        tables:
          t_emp:
            actual-data-nodes: ds-default.t_emp
            key-generator-column-name: eid
          t_order:
            actual-data-nodes: ds-$->{0..1}.t_order_$->{0..1}
            table-strategy: 
              inline: 
                sharding-column: order_id
                algorithm-expression: t_order_$->{order_id % 2}
            database-strategy:
              inline:
                sharding-column: user_id
                algorithm-expression: ds-$->{user_id % 2}
            key-generator-column-name: order_id
          t_order_item:
            actual-data-nodes: ds-$->{0..1}.t_order_item_$->{0..1}
            table-strategy: 
              inline: 
                sharding-column: order_id
                algorithm-expression: t_order_item_$->{order_id % 2}
            database-strategy:
              inline:
                sharding-column: user_id
                algorithm-expression: ds-$->{user_id % 2}
            key-generator-column-name: order_item_id
        master-slave-rules:
          ds-0:
            master-data-source-name: ds-master-0
            slave-data-source-names: ds-master-0-slave-0, ds-master-0-slave-1
          ds-1:
            master-data-source-name: ds-master-1
            slave-data-source-names: ds-master-1-slave-0, ds-master-1-slave-1
        props:
          sql:
            show: true
      orchestration:
        name: demo_spring_boot_ds_share_kafka
        type: SHARDING
        overwrite: false
        zookeeper:
          namespace: orchestration-spring-boot-share-kafka
          server-lists: 192.168.0.3:2181

**Comment by olderzhou** [comment]
其实主要是由于DDL-AUTO属性决定，create的时候会删掉已存在的表，所以一切都ok，validate的时候会去校验表结构，但是我感觉校验的时候对数据源应用规则出现问题了，create，none都是没问题的，update，validate均会报错

**Comment by tristaZero** [comment]
Hi, please check your configuration here:
```
default-database-strategy:
      inline:
        sharding-column: user_id
        algorithm-expression: ds-$->{user_id % 2}
    binding-tables: 
    tables:
      t_emp:
        actual-data-nodes: ds-default.t_emp
        key-generator-column-name: eid
```
