### ISSUE TITLE
Sharding-Proxy master-slave mode  Exception（Springboot+mybatis）

### ISSUE THREAD

**Issue by amanxu** [sharding-sphere/sharding-sphere#1403]
### PS: The example codes is normal when use sharding-jdbc or no use Sharding-Sphere, But it throw exception when I use Sharding-Proxy. My Sharding-Proxy service is normal and can be connected by navicat.
 SQL: select u.id,u.user_name,u.real_name,u.phone,u.email,u.user_type,u.deleted from elegant_user u WHERE   u.user_name =  #{userName,jdbcType=VARCHAR}
### The Exception  is described below:
#Error querying database. Cause: java.sql.SQLException: Statement parameter 1 not set.
#The error may exist in file [D:\githubwork\elegant-essay\target\classes\mapper\UserSelfMapper.xml]
#The error may involve com.elegant.essay.mapper.UserSelfMapper.findUserByAccount-Inline
#The error occurred while setting parameters
#SQL: select u.id, u.user_name, u.password, u.real_name, u.phone, u.email, u.user_type, u.deleted from elegant_user u WHERE u.user_name = ?
#Cause: java.sql.SQLException: Statement parameter 1 not set.
; SQL []; Statement parameter 1 not set.; nested exception is java.sql.SQLException: Statement parameter 1 not set.] with root cause
java.sql.SQLException: Statement parameter 1 not set.
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1283)
at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:783)
at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3409)
at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3407)
at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167)
at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)
at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:142)
at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
at com.sun.proxy.$Proxy116.query(Unknown Source)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
at com.sun.proxy.$Proxy74.selectOne(Unknown Source)
at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:83)
at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
at com.sun.proxy.$Proxy78.findUserByAccount(Unknown Source)
at com.elegant.essay.service.impl.UserServiceImpl.findUserByAccount(UserServiceImpl.java:136)

**Comment by amanxu** [comment]
I pull sharding-sphere-example project from github and run "sharding-proxy-boot-mybatis-example" project which also throw the same exception.

**Comment by amanxu** [comment]
I pull sharding-sphere-example project from github and run "sharding-proxy-boot-mybatis-example" project which also throw the same exception.

**Comment by beckhampu** [comment]
@amanxu ,Thanks for your issue, we will fix this problem.

**Comment by amanxu** [comment]
Sorry, I don't understand your reply for #1406

**Comment by beckhampu** [comment]
@amanxu ，the reason for this problem is that when setting the parameters, the parameters obtained from SQLUnit are empty。So my pr（#1406） set the parameters when building SQLUnit 。You can refer to the PreparedStatementExecutorWrapper.createStatement () method.

**Comment by terrymanu** [comment]
fixed at 3.0.1

**Comment by amanxu** [comment]
Thanks for your answer.Expect the 3.0.1 release.
