### ISSUE TITLE
是否支持left join 子查询

### ISSUE THREAD

**Issue by tengfeineu** [sharding-sphere/sharding-sphere#1568]
### Which version of Sharding-Sphere did you use?
<dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>3.0.0.M1</version>
        </dependency>
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
 Sharding-JDBC
### Expected behavior
not exception

### Cause: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 91 common frames omitted
Caused by: java.lang.NullPointerException: null
	at io.shardingsphere.core.jdbc.metadata.dialect.JDBCShardingRefreshHandler.execute(JDBCShardingRefreshHandler.java:49)
	at io.shardingsphere.core.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:159)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy181.query(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 97 common frames omitted
### Reason analyze (If you can)

http://shardingsphere.io/document/current/cn/features/sharding/usage-standard/sql/

### Example codes for reproduce this issue (such as a github link).

SELECT
	count(u.uid) AS channelCount,
	c.channel_id AS channelId,
	c.NAME AS channelName
FROM
	lm_channel_t c
LEFT JOIN (
	SELECT
		us.uid,
		us.initial_channel_id
	FROM
		lm_user_t_2 us
	WHERE
		DATE_FORMAT(us.create_time, '%Y-%m-%d') = date_add(CURDATE(), INTERVAL - 1 DAY)
) u ON c.channel_id = u.initial_channel_id
GROUP BY
	c.channel_id

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
