### ISSUE TITLE
SQL keyword in does not support the parameter of empty list

### ISSUE THREAD

**Issue by 2YSP** [sharding-sphere/sharding-sphere#1585]
# this is my code,the sharding jdbc version is 3.0.0
```java

 @Test
    public void test(){

//        List<ParkPayChannel> channels = parkPayChannelDao.selectListInParkCode(Arrays.asList("6100005853", "6100003064"));
        List<String> list = Lists.newArrayList();
        List<ParkPayChannel> channels = parkPayChannelDao.selectListInParkCode(list);
        System.out.println(channels.size());

    }
```
# and my sql:
```xml

    <select id="selectListInParkCode" parameterType="java.util.List" resultType="XX.ParkPayChannel">
        select * from _park_pay_channel where park_code in
        <foreach collection="list" index="index" separator="," open="(" close=")" item="code">
            #{code}
        </foreach>
    </select>
```
# error logs:
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'LEFT_PAREN', actual token is 'END', literals is ''.

	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy112.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:139)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:76)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy117.selectListInParkCode(Unknown Source)
	at com.chinaroad.open.ApplicationTests.test(ApplicationTests.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'LEFT_PAREN', actual token is 'END', literals is ''.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 37 more
Caused by: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'LEFT_PAREN', actual token is 'END', literals is ''.
	at io.shardingsphere.core.parsing.lexer.LexerEngine.accept(LexerEngine.java:122)
	at io.shardingsphere.core.parsing.parser.clause.WhereClauseParser.parseInCondition(WhereClauseParser.java:225)
	at io.shardingsphere.core.parsing.parser.clause.WhereClauseParser.parseComparisonCondition(WhereClauseParser.java:170)
	at io.shardingsphere.core.parsing.parser.clause.WhereClauseParser.parseAnd(WhereClauseParser.java:127)
	at io.shardingsphere.core.parsing.parser.clause.WhereClauseParser.parseOr(WhereClauseParser.java:112)
	at io.shardingsphere.core.parsing.parser.clause.WhereClauseParser.parseWhere(WhereClauseParser.java:94)
	at io.shardingsphere.core.parsing.parser.clause.WhereClauseParser.parse(WhereClauseParser.java:89)
	at io.shardingsphere.core.parsing.parser.sql.dql.select.AbstractSelectParser.parseWhere(AbstractSelectParser.java:112)
	at io.shardingsphere.core.parsing.parser.dialect.mysql.sql.MySQLSelectParser.parseInternal(MySQLSelectParser.java:52)
	at io.shardingsphere.core.parsing.parser.sql.dql.select.AbstractSelectParser.parseInternal(AbstractSelectParser.java:80)
	at io.shardingsphere.core.parsing.parser.sql.dql.select.AbstractSelectParser.parse(AbstractSelectParser.java:67)
	at io.shardingsphere.core.parsing.parser.sql.dql.select.AbstractSelectParser.parse(AbstractSelectParser.java:51)
	at io.shardingsphere.core.parsing.SQLParsingEngine.parse(SQLParsingEngine.java:60)
	at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.parse(ParsingSQLRouter.java:91)
	at io.shardingsphere.core.routing.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:64)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.sqlRoute(ShardingPreparedStatement.java:229)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:137)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 43 more

**Comment by terrymanu** [comment]
Please show.show and paste log here

**Comment by 2YSP** [comment]
2018-12-17 16:19:17.741 DEBUG [main][SqlSessionUtils][getSqlSession] -  Creating a new SqlSession
2018-12-17 16:19:17.745 DEBUG [main][SqlSessionUtils][registerSessionHolder] -  SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@39e91bda] was not registered for synchronization because synchronization is not active
2018-12-17 16:19:17.767 DEBUG [main][DataSourceUtils][doGetConnection] -  Fetching JDBC Connection from DataSource
2018-12-17 16:19:17.773 DEBUG [main][SpringManagedTransaction][openConnection] -  JDBC Connection [io.shardingsphere.shardingjdbc.jdbc.core.connection.ShardingConnection@106c3e0a] will not be managed by Spring
2018-12-17 16:19:17.775 DEBUG [main][BaseJdbcLogger][debug] -  ==>  Preparing: select * from _park_pay_channel where park_code in 
2018-12-17 16:19:17.792 DEBUG [main][BaseJdbcLogger][debug] -  ==> Parameters: 
2018-12-17 16:19:17.821 DEBUG [main][SqlSessionUtils][closeSqlSession] -  Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@39e91bda]
2018-12-17 16:19:17.822 DEBUG [main][DataSourceUtils][doReleaseConnection] -  Returning JDBC Connection to DataSource
2018-12-17 16:19:17.826 DEBUG [main][DefaultCacheAwareContextLoaderDelegate][loadContext] -  Retrieved ApplicationContext from cache with key [[WebMergedContextConfiguration@478ee483 testClass = CashierServicesApplicationTests, locations = '{}', classes = '{class com.chinaroad.open.CashierServicesApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[[ImportsContextCustomizer@1a7288a3 key = [@org.junit.runner.RunWith(value=class org.springframework.test.context.junit4.SpringRunner), @org.springframework.test.context.BootstrapWith(value=class org.springframework.boot.test.context.SpringBootTestContextBootstrapper), @org.mybatis.spring.annotation.MapperScan(sqlSessionFactoryRef=, sqlSessionTemplateRef=, annotationClass=interface java.lang.annotation.Annotation, basePackageClasses=[], markerInterface=class java.lang.Class, nameGenerator=interface org.springframework.beans.factory.support.BeanNameGenerator, basePackages=[com.chinaroad.open.dao.cashier, com.chinaroad.open.dao.park], value=[], factoryBean=class org.mybatis.spring.mapper.MapperFactoryBean), @org.springframework.boot.test.context.SpringBootTest(webEnvironment=MOCK, value=[], properties=[], classes=[]), @org.springframework.context.annotation.Import(value=[class org.mybatis.spring.annotation.MapperScannerRegistrar])]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7857fe2, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@29d80d2b, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@3aa078fd, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@45385f75], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]]
2018-12-17 16:19:17.826 DEBUG [main][DefaultContextCache][logStatistics] -  Spring test ApplicationContext cache statistics: [DefaultContextCache@334ac669 size = 1, maxSize = 32, parentContextCount = 0, hitCount = 3, missCount = 1]
2018-12-17 16:19:17.826 DEBUG [main][DefaultCacheAwareContextLoaderDelegate][loadContext] -  Retrieved ApplicationContext from cache with key [[WebMergedContextConfiguration@478ee483 testClass = CashierServicesApplicationTests, locations = '{}', classes = '{class com.chinaroad.open.CashierServicesApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[[ImportsContextCustomizer@1a7288a3 key = [@org.junit.runner.RunWith(value=class org.springframework.test.context.junit4.SpringRunner), @org.springframework.test.context.BootstrapWith(value=class org.springframework.boot.test.context.SpringBootTestContextBootstrapper), @org.mybatis.spring.annotation.MapperScan(sqlSessionFactoryRef=, sqlSessionTemplateRef=, annotationClass=interface java.lang.annotation.Annotation, basePackageClasses=[], markerInterface=class java.lang.Class, nameGenerator=interface org.springframework.beans.factory.support.BeanNameGenerator, basePackages=[com.chinaroad.open.dao.cashier, com.chinaroad.open.dao.park], value=[], factoryBean=class org.mybatis.spring.mapper.MapperFactoryBean), @org.springframework.boot.test.context.SpringBootTest(webEnvironment=MOCK, value=[], properties=[], classes=[]), @org.springframework.context.annotation.Import(value=[class org.mybatis.spring.annotation.MapperScannerRegistrar])]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7857fe2, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@29d80d2b, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@3aa078fd, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@45385f75], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]]
2018-12-17 16:19:17.827 DEBUG [main][DefaultContextCache][logStatistics] -  Spring test ApplicationContext cache statistics: [DefaultContextCache@334ac669 size = 1, maxSize = 32, parentContextCount = 0, hitCount = 4, missCount = 1]
2018-12-17 16:19:17.828 DEBUG [main][DefaultCacheAwareContextLoaderDelegate][loadContext] -  Retrieved ApplicationContext from cache with key [[WebMergedContextConfiguration@478ee483 testClass = CashierServicesApplicationTests, locations = '{}', classes = '{class com.chinaroad.open.CashierServicesApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[[ImportsContextCustomizer@1a7288a3 key = [@org.junit.runner.RunWith(value=class org.springframework.test.context.junit4.SpringRunner), @org.springframework.test.context.BootstrapWith(value=class org.springframework.boot.test.context.SpringBootTestContextBootstrapper), @org.mybatis.spring.annotation.MapperScan(sqlSessionFactoryRef=, sqlSessionTemplateRef=, annotationClass=interface java.lang.annotation.Annotation, basePackageClasses=[], markerInterface=class java.lang.Class, nameGenerator=interface org.springframework.beans.factory.support.BeanNameGenerator, basePackages=[com.chinaroad.open.dao.cashier, com.chinaroad.open.dao.park], value=[], factoryBean=class org.mybatis.spring.mapper.MapperFactoryBean), @org.springframework.boot.test.context.SpringBootTest(webEnvironment=MOCK, value=[], properties=[], classes=[]), @org.springframework.context.annotation.Import(value=[class org.mybatis.spring.annotation.MapperScannerRegistrar])]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7857fe2, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@29d80d2b, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@3aa078fd, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@45385f75], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]]
2018-12-17 16:19:17.828 DEBUG [main][DefaultContextCache][logStatistics] -  Spring test ApplicationContext cache statistics: [DefaultContextCache@334ac669 size = 1, maxSize = 32, parentContextCount = 0, hitCount = 5, missCount = 1]
2018-12-17 16:19:17.830 DEBUG [main][DefaultCacheAwareContextLoaderDelegate][loadContext] -  Retrieved ApplicationContext from cache with key [[WebMergedContextConfiguration@478ee483 testClass = CashierServicesApplicationTests, locations = '{}', classes = '{class com.chinaroad.open.CashierServicesApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[[ImportsContextCustomizer@1a7288a3 key = [@org.junit.runner.RunWith(value=class org.springframework.test.context.junit4.SpringRunner), @org.springframework.test.context.BootstrapWith(value=class org.springframework.boot.test.context.SpringBootTestContextBootstrapper), @org.mybatis.spring.annotation.MapperScan(sqlSessionFactoryRef=, sqlSessionTemplateRef=, annotationClass=interface java.lang.annotation.Annotation, basePackageClasses=[], markerInterface=class java.lang.Class, nameGenerator=interface org.springframework.beans.factory.support.BeanNameGenerator, basePackages=[com.chinaroad.open.dao.cashier, com.chinaroad.open.dao.park], value=[], factoryBean=class org.mybatis.spring.mapper.MapperFactoryBean), @org.springframework.boot.test.context.SpringBootTest(webEnvironment=MOCK, value=[], properties=[], classes=[]), @org.springframework.context.annotation.Import(value=[class org.mybatis.spring.annotation.MapperScannerRegistrar])]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7857fe2, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@29d80d2b, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@3aa078fd, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@45385f75], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]]
2018-12-17 16:19:17.830 DEBUG [main][DefaultContextCache][logStatistics] -  Spring test ApplicationContext cache statistics: [DefaultContextCache@334ac669 size = 1, maxSize = 32, parentContextCount = 0, hitCount = 6, missCount = 1]
2018-12-17 16:19:17.830 DEBUG [main][AbstractBeanFactory][doGetBean] -  Returning cached instance of singleton bean 'org.springframework.boot.test.mock.mockito.MockitoBeans'
2018-12-17 16:19:17.830 DEBUG [main][AbstractDirtiesContextTestExecutionListener][beforeOrAfterTestMethod] -  After test method: context [DefaultTestContext@abf688e testClass = CashierServicesApplicationTests, testInstance = com.chinaroad.open.CashierServicesApplicationTests@4468ced2, testMethod = contextLoads@CashierServicesApplicationTests, testException = org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'LEFT_PAREN', actual token is 'END', literals is ''.
### The error may exist in class path resource [com/chinaroad/open/mapper/park/ParkPayChannelMapper.xml]
### The error may involve com.chinaroad.open.dao.park.ParkPayChannelDao.selectListInParkCode-Inline
### The error occurred while setting parameters
### SQL: select * from _park_pay_channel where park_code in
### Cause: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'LEFT_PAREN', actual token is 'END', literals is ''., mergedContextConfiguration = [WebMergedContextConfiguration@478ee483 testClass = CashierServicesApplicationTests, locations = '{}', classes = '{class com.chinaroad.open.CashierServicesApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[[ImportsContextCustomizer@1a7288a3 key = [@org.junit.runner.RunWith(value=class org.springframework.test.context.junit4.SpringRunner), @org.springframework.test.context.BootstrapWith(value=class org.springframework.boot.test.context.SpringBootTestContextBootstrapper), @org.mybatis.spring.annotation.MapperScan(sqlSessionFactoryRef=, sqlSessionTemplateRef=, annotationClass=interface java.lang.annotation.Annotation, basePackageClasses=[], markerInterface=class java.lang.Class, nameGenerator=interface org.springframework.beans.factory.support.BeanNameGenerator, basePackages=[com.chinaroad.open.dao.cashier, com.chinaroad.open.dao.park], value=[], factoryBean=class org.mybatis.spring.mapper.MapperFactoryBean), @org.springframework.boot.test.context.SpringBootTest(webEnvironment=MOCK, value=[], properties=[], classes=[]), @org.springframework.context.annotation.Import(value=[class org.mybatis.spring.annotation.MapperScannerRegistrar])]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7857fe2, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@29d80d2b, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@3aa078fd, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@45385f75], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.web.ServletTestExecutionListener.activateListener' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.populatedRequestContextHolder' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.resetRequestContextHolder' -> true]], class annotated with @DirtiesContext [false] with mode [null], method annotated with @DirtiesContext [false] with mode [null].
2018-12-17 16:19:17.836 DEBUG [main][ServletTestExecutionListener][afterTestMethod] -  Resetting RequestContextHolder for test context [DefaultTestContext@abf688e testClass = CashierServicesApplicationTests, testInstance = com.chinaroad.open.CashierServicesApplicationTests@4468ced2, testMethod = contextLoads@CashierServicesApplicationTests, testException = org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'LEFT_PAREN', actual token is 'END', literals is ''.
### The error may exist in class path resource [com/chinaroad/open/mapper/park/ParkPayChannelMapper.xml]
### The error may involve com.chinaroad.open.dao.park.ParkPayChannelDao.selectListInParkCode-Inline
### The error occurred while setting parameters
### SQL: select * from _park_pay_channel where park_code in
### Cause: io.shardingsphere.core.parsing.parser.exception.SQLParsingException: SQL syntax error, expected token is 'LEFT_PAREN', actual token is 'END', literals is ''., mergedContextConfiguration = [WebMergedContextConfiguration@478ee483 testClass = CashierServicesApplicationTests, locations = '{}', classes = '{class com.chinaroad.open.CashierServicesApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[[ImportsContextCustomizer@1a7288a3 key = [@org.junit.runner.RunWith(value=class org.springframework.test.context.junit4.SpringRunner), @org.springframework.test.context.BootstrapWith(value=class org.springframework.boot.test.context.SpringBootTestContextBootstrapper), @org.mybatis.spring.annotation.MapperScan(sqlSessionFactoryRef=, sqlSessionTemplateRef=, annotationClass=interface java.lang.annotation.Annotation, basePackageClasses=[], markerInterface=class java.lang.Class, nameGenerator=interface org.springframework.beans.factory.support.BeanNameGenerator, basePackages=[com.chinaroad.open.dao.cashier, com.chinaroad.open.dao.park], value=[], factoryBean=class org.mybatis.spring.mapper.MapperFactoryBean), @org.springframework.boot.test.context.SpringBootTest(webEnvironment=MOCK, value=[], properties=[], classes=[]), @org.springframework.context.annotation.Import(value=[class org.mybatis.spring.annotation.MapperScannerRegistrar])]], org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@7857fe2, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@29d80d2b, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@3aa078fd, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@45385f75], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.web.ServletTestExecutionListener.activateListener' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.populatedRequestContextHolder' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.resetRequestContextHolder' -> true]].

**Comment by terrymanu** [comment]
Hi, this is not log of`sql.show`, please read document  and paste `show.show` log here

**Comment by 2YSP** [comment]
不好意思，是这个吗？
```java
Map<String, Object> configMap = new HashMap<>();
        Properties props = new Properties();
        props.put(ShardingPropertiesConstant.SQL_SHOW.getKey(),true);
        return ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfig, configMap, props);
```

**Comment by terrymanu** [comment]
Yes, please show your log

**Comment by 2YSP** [comment]
![_20181221155209](https://user-images.githubusercontent.com/22067095/50331080-6ad28600-0538-11e9-8c9b-815628abe2e7.png)

**Comment by terrymanu** [comment]
you can try to 3.1.0.M1
