### ISSUE TITLE
sharding-sphere 多数据源和分表配置和读写分离支持

### ISSUE THREAD

**Issue by JohnsonChenFuD** [sharding-sphere/sharding-sphere#1600]
## Question
现在有个问题，sharding-sphere 多数据源和分表配置和读写分离支持
三个数据源 A，B ，C，每一个数据源都需要进行读写分离
数据源A 有表：
user_info_000 ~user_info_512;配置分表策略；
operation_trade 非分表；
数据源B 有表：comic_000~ comic_512 ;配置分表策略
comic_operation_trade 非分表；
数据源C 有表；
member_free ;
xxx
现在使用sharding-sphere 配置，

 @Bean
    public Map<String, DataSource> createDataSourceMap() {
        final Map<String, DataSource> dataSourceMap = new HashMap<>(6);
        // 配置多数据源
        dataSourceMap.put(Constants.MASTER_DB_TYPE, writeDataSource());
        dataSourceMap.put(Constants.SLAVE_DB_TYPE, readDataSource());

        dataSourceMap.put(Constants.ORDER_MASTER_DB_TYPE, comicOrderWriteDataSource());
        dataSourceMap.put(Constants.ORDER_SLAVE_DB_TYPE,comicOrderReadDataSource());

        dataSourceMap.put(Constants.GROWTH_MASTER_DB_TYPE, growthWriteDataSource());
        dataSourceMap.put(Constants.GROWTH_SLAVE_DB_TYPE, growthReadDataSource());

        return dataSourceMap;
    }
    @Bean
    public DataSource getShardingDataSource() throws SQLException {
        ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
        shardingRuleConfig.setDefaultDataSourceName("A");
        shardingRuleConfig.setMasterSlaveRuleConfigs(getMasterSlaveRuleConfigurations());
        shardingRuleConfig.getTableRuleConfigs().add(getGrowthUserTableRuleConfiguration());
        shardingRuleConfig.getTableRuleConfigs().add(getComicUserTableRuleConfiguration());
        shardingRuleConfig.getBindingTableGroups().add("gr_user_info, comic_user_info");
        //shardingRuleConfig.setDefaultTableShardingStrategyConfig(new StandardShardingStrategyConfiguration("uid", new ModuloShardingTableAlgorithm()));
        return ShardingDataSourceFactory.createDataSource(createDataSourceMap(), shardingRuleConfig, new ConcurrentHashMap(), new Properties());
    }

    @Bean
    public TableRuleConfiguration getGrowthUserTableRuleConfiguration() {
        TableRuleConfiguration growthTableRuleConfig = new TableRuleConfiguration();
        growthTableRuleConfig.setLogicTable("user_info");
        growthTableRuleConfig.setActualDataNodes("A.user_info_${def tmp=[];(0..511).each {e->tmp.add(String.format(\"%04d\",e))};return tmp}");
        growthTableRuleConfig.setTableShardingStrategyConfig(new StandardShardingStrategyConfiguration("uid", new ModuloShardingTableAlgorithm()));
        return growthTableRuleConfig;
    }

    @Bean
    public TableRuleConfiguration getComicUserTableRuleConfiguration() {
        TableRuleConfiguration comicTableRuleConfig = new TableRuleConfiguration();
        comicTableRuleConfig.setLogicTable("comic");
        comicTableRuleConfig.setActualDataNodes("comic.comic_${def tmp=[];(0..511).each {e->tmp.add(String.format(\"%04d\",e))};return tmp}");
        comicTableRuleConfig.setTableShardingStrategyConfig(new StandardShardingStrategyConfiguration("uid", new ModuloShardingTableAlgorithm()));

        return comicTableRuleConfig;
    }

    @Bean
    public List<MasterSlaveRuleConfiguration> getMasterSlaveRuleConfigurations() {
        List masterSlaveConfig = Lists.newArrayList();

        MasterSlaveRuleConfiguration comicMasterSlaveRule = new MasterSlaveRuleConfiguration();
        comicMasterSlaveRule.setName("B");
        comicMasterSlaveRule.setMasterDataSourceName(Constants.MASTER_DB_TYPE);
        comicMasterSlaveRule.setSlaveDataSourceNames(Arrays.asList(Constants.SLAVE_DB_TYPE));
        masterSlaveConfig.add(comicMasterSlaveRule);

        MasterSlaveRuleConfiguration comicOrderMasterSlaveRule = new MasterSlaveRuleConfiguration();
        comicOrderMasterSlaveRule.setName("C");
        comicOrderMasterSlaveRule.setMasterDataSourceName(Constants.ORDER_MASTER_DB_TYPE);
        comicOrderMasterSlaveRule.setSlaveDataSourceNames(Arrays.asList(Constants.ORDER_SLAVE_DB_TYPE));
        masterSlaveConfig.add(comicOrderMasterSlaveRule);

        MasterSlaveRuleConfiguration growthMasterSlaveRule = new MasterSlaveRuleConfiguration();
        growthMasterSlaveRule.setName("A");
        growthMasterSlaveRule.setMasterDataSourceName(Constants.GROWTH_MASTER_DB_TYPE);
        growthMasterSlaveRule.setSlaveDataSourceNames(Arrays.asList(Constants.GROWTH_SLAVE_DB_TYPE));
        masterSlaveConfig.add(growthMasterSlaveRule);

        return masterSlaveConfig;
    }

针对数据源B 的comic_operation_trade 进行插入操作 会报如下错误：
org.springframework.jdbc.BadSqlGrammarException: 
[INFO ] 2018-12-12 14:10:37,098 --main-- [org.springframework.jdbc.support.SQLErrorCodesFactory] SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana] 
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'growth_test.member_free' doesn't exist
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'A.comic_operation_trade' doesn't exist
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy117.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:57)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy119.insertMemberFree(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy120.insertMemberFree(Unknown Source)
	at com.iqiyi.comic.monthlymemberservice.service.Impl.MemberFreeServiceImpl.markMemberFreeInfo(MemberFreeServiceImpl.java:32)
	at com.iqiyi.comic.monthlymemberservice.MonthlymemberserviceApplicationTests.insertMemberFreeInfo(MonthlymemberserviceApplicationTests.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'growth_test.member_free' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2494)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2931)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2929)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:131)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
	at io.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$4.executeSQL(PreparedStatementExecutor.java:158)
	at io.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$4.executeSQL(PreparedStatementExecutor.java:154)
	at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:85)
	at io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:69)
	at io.shardingsphere.core.executor.ShardingExecuteEngine.syncGroupExecute(ShardingExecuteEngine.java:182)
	at io.shardingsphere.core.executor.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:158)
	at io.shardingsphere.core.executor.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:71)
	at io.shardingsphere.core.executor.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:54)
	at io.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:122)
	at io.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:161)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy173.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.ReuseExecutor.doUpdate(ReuseExecutor.java:52)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 46 more

查找资料 应该是 这一句 的原因：
 shardingRuleConfig.setDefaultDataSourceName("A");
非分表的规则 默认的是数据源A ，这里不能设置多个默认的数据源，假设数据源B 中的非分表要进行茶树操作就会报上面的错误。
目前sharding-spere 能够解决吗？

**Comment by JohnsonChenFuD** [comment]
多个数据源，有的源要进行分表 有的源不进行分表，设置其中一个数据源A，要对B源中的非分表进行插入操作就会报错了。

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.

**Comment by Ah39** [comment]
@JohnsonChenFuD 版本号多少，我这边两个数据源也遇到了类似的问题。3.1.0 版本线上重启会报找不到数据库
