### ISSUE TITLE
 waiting to lock

### ISSUE THREAD

**Issue by zhanglei** [sharding-sphere/sharding-sphere#1612]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere did you use?
3.0.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
 Sharding-Proxy
### Example codes for reproduce this issue (such as a github link).

"epollEventLoopGroup-4-46" #203 prio=10 os_prio=0 tid=0x00007fbf9c003800 nid=0x21d4 waiting for monitor entry [0x00007fbfc0924000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at io.shardingsphere.shardingproxy.backend.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:129)
	- waiting to lock <0x00000000c02a3060> (a com.zaxxer.hikari.HikariDataSource)
	at io.shardingsphere.shardingproxy.backend.jdbc.connection.BackendConnection.getConnections(BackendConnection.java:74)
	at io.shardingsphere.shardingproxy.backend.jdbc.execute.JDBCExecuteEngine$ProxyJDBCExecutePrepareCallback.getConnections(JDBCExecuteEngine.java:181)
	at io.shardingsphere.core.executor.sql.prepare.SQLExecutePrepareTemplate.getSQLExecuteGroups(SQLExecutePrepareTemplate.java:112)
	at io.shardingsphere.core.executor.sql.prepare.SQLExecutePrepareTemplate.access$000(SQLExecutePrepareTemplate.java:49)
	at io.shardingsphere.core.executor.sql.prepare.SQLExecutePrepareTemplate$1.execute(SQLExecutePrepareTemplate.java:85)
	at io.shardingsphere.core.executor.sql.prepare.SQLExecutePrepareTemplate$1.execute(SQLExecutePrepareTemplate.java:81)
	at io.shardingsphere.core.executor.ShardingExecuteEngine.syncExecute(ShardingExecuteEngine.java:109)
	at io.shardingsphere.core.executor.ShardingExecuteEngine.execute(ShardingExecuteEngine.java:89)
	at io.shardingsphere.core.executor.ShardingExecuteEngine.execute(ShardingExecuteEngine.java:68)
	at io.shardingsphere.core.executor.sql.prepare.SQLExecutePrepareTemplate.getAsynchronizedExecuteUnitGroups(SQLExecutePrepareTemplate.java:80)
	at io.shardingsphere.core.executor.sql.prepare.SQLExecutePrepareTemplate.getExecuteUnitGroups(SQLExecutePrepareTemplate.java:64)
	at io.shardingsphere.shardingproxy.backend.jdbc.execute.JDBCExecuteEngine.execute(JDBCExecuteEngine.java:113)
	at io.shardingsphere.shardingproxy.backend.jdbc.JDBCBackendHandler.execute(JDBCBackendHandler.java:96)
	at io.shardingsphere.shardingproxy.backend.jdbc.JDBCBackendHandler.execute0(JDBCBackendHandler.java:84)
	at io.shardingsphere.shardingproxy.backend.AbstractBackendHandler.execute(AbstractBackendHandler.java:37)
	at io.shardingsphere.shardingproxy.transport.mysql.packet.command.query.text.query.ComQueryPacket.execute(ComQueryPacket.java:92)
	at io.shardingsphere.shardingproxy.frontend.mysql.MySQLFrontendHandler$CommandExecutor.run(MySQLFrontendHandler.java:125)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zhanglei** [comment]
1.server.yaml
props:
  max.connections.size.per.query: 128
  acceptor.size: 64  # The default value is available processors count * 2.
  executor.size: 64  # Infinite by default.
  proxy.transaction.enabled: false
  proxy.opentracing.enabled: false
  sql.show: false


2. dataSources
    autoCommit: true
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 50
3. sql
![image](https://user-images.githubusercontent.com/241508/49915934-3d039680-fed3-11e8-962f-ab048fdd8fd5.png)

**Comment by tuohai666** [comment]
Expected behavior
Actual behavior

I'd like to ask more simple simply: Is your SQL executed well? If not what did you see from your mysql-client?

**Comment by zhanglei** [comment]
Adjust maximumPoolSize and max.connections.size.per.query can be resolved
