### ISSUE TITLE
关于复合分片有部分分片键值为 null 报错问题。

### ISSUE THREAD

**Issue by lqtcts** [sharding-sphere/sharding-sphere#1709]
场景说明：

有如下SQL:
INSERT INTO task_execute_task_flow ` (` id `, ` merchant_id `, ` distributor_id `, ` promoter_id `, ` promote_action_id `, ` web_site_code `, ` sys_id `, ` asin `, ` taobaolink `, ` web_store_name `, ` promote_task_id `, ` plan_id `, ` promote_plan_list_id `, ` listing_id `, ` buy_account_id `, ` promoter_taobao `, ` STATUS `, ` task_type `, ` merchant_coin `, ` distributor_coin `, ` promoter_coin `, ` referee_coin `, ` plan_start_time `, ` plan_end_time `, ` real_start_time `, ` real_end_time `, ` submit_time `, ` quick_run `, ` audit_time `, ` note `, ` fail_reason_type `, ` fail_reason `, ` DATA `, ` settle_status `, ` settle_time `, ` restart_times `, ` reassign_times `, ` reassign_execute_task_id `, ` version `, ` gmt_create `, ` gmt_modify `) VALUES ('1545382425497002', '1524468562379637', '300001', NULL, '3', NULL, '401417973', '562498001983', NULL, 'XXXXX', '1545382425090001', '1545382423784051', '1545382423827052', '1545382422105005', NULL, NULL, '6', '8', '4.8', '3.6', '0', '0', '2018-12-21 16:53:12', '2048-12-21 16:53:12', NULL, '2018-12-24 14:53:24', NULL, b'0', NULL, '', NULL, '', '{}', '0', '2018-12-24 14:53:24', NULL, NULL, NULL, '1545634403801980', '2018-12-21 16:53:45', NULL);

分片策略：
 new ComplexShardingStrategyConfiguration("promote_task_id,gmt_create,real_start_time"）

报错信息：

### io.shardingsphere.core.exception.ShardingException: Parameter `null` should extends Comparable for sharding value.

	at io.shardingsphere.core.parsing.parser.context.condition.Condition.getConditionValues(Condition.java:130)
	at io.shardingsphere.core.optimizer.insert.InsertOptimizeEngine.getShardingCondition(InsertOptimizeEngine.java:117)
	at io.shardingsphere.core.optimizer.insert.InsertOptimizeEngine.optimize(InsertOptimizeEngine.java:102)
	at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.route(ParsingSQLRouter.java:109)
	at io.shardingsphere.core.routing.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:66)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.sqlRoute(ShardingPreparedStatement.java:229)
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeUpdate(ShardingPreparedStatement.java:124)
	at org.springframework.jdbc.core.JdbcTemplate$3.doInPreparedStatement(JdbcTemplate.java:907)
	at org.springframework.jdbc.core.JdbcTemplate$3.doInPreparedStatement(JdbcTemplate.java:904)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:904)
	at com.teynet.frame.repo.core.NormalRepository.insert(NormalRepository.java:64)
	at ApplicationTests.update(ApplicationTests.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

疑问：

官网称：
对应ComplexShardingStrategy。复合分片策略。提供对SQL语句中的=, IN和BETWEEN AND的分片操作支持。ComplexShardingStrategy支持多分片键，由于多分片键之间的关系复杂，因此并未进行过多的封装，而是直接将分片键值组合以及分片操作符透传至分片算法，完全由应用开发者实现，提供最大的灵活度。

实际上，代码在运行到自定义算法之前，被校验分片键的值必须实现Comparable 接口，这比没有想象中灵活啊？？？！！！，你们觉得呢？

![image](https://user-images.githubusercontent.com/8100331/50627962-ed176d00-0f70-11e9-84d1-074116750ce8.png)

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
