### ISSUE TITLE
sharding jdbc 3.1.0 sql error

### ISSUE THREAD

**Issue by lazeyliu** [sharding-sphere/sharding-sphere#1746]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:
sharding jdbc version:
```xml
  <dependency>
            <groupId>io.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>3.1.0</version>
   </dependency>
```
the configration is #1653
the sql is #1658
like this :
```sql
SELECT COUNT(1) FROM ( 
     SELECT
        r.`channel` as `channel_code`,
        r.`channel_name` as `channel_name`,
        COUNT(r.id) `total_cnt`,
        COUNT(r.connect_flag = "Y") `connected_cnt`
        FROM record_callin r
        LEFT JOIN sys_org_tree_rel tree ON tree.teamid = r.teamid
        LEFT JOIN sys_user u ON u.brokerid = r.brokerid
        where
        r.create_time >= '2018-01-01 00:00:00' and r.create_time <=  '2019-01-01 00:00:00'
        GROUP BY 
        r.`channel` 
) TOTAL
```
this throws an error:
```
Caused by: java.lang.IllegalStateException: Must have sharding column with subquery.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[guava-20.0.jar:na]
	at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.mergeShardingValueForSubQuery(ParsingSQLRouter.java:154) ~[sharding-core-3.1.0.jar:na]
	at io.shardingsphere.core.routing.router.sharding.ParsingSQLRouter.route(ParsingSQLRouter.java:100) ~[sharding-core-3.1.0.jar:na]
	at io.shardingsphere.core.routing.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:64) ~[sharding-core-3.1.0.jar:na]
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.sqlRoute(ShardingPreparedStatement.java:214) ~[sharding-jdbc-core-3.1.0.jar:na]
	at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:106) ~[sharding-jdbc-core-3.1.0.jar:na]
	at com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor.queryTotal(PaginationInterceptor.java:207) ~[mybatis-plus-extension-3.0.6.jar:3.0.6]
	... 119 common frames omitted
```

**sharding column is create_time**

**Comment by terrymanu** [comment]
Hi, this is expected exception, please try to understand message of exception
