### ISSUE TITLE
hibernate hql查询oracle报错

### ISSUE THREAD

**Issue by meta-life** [sharding-sphere/sharding-sphere#638]
使用的Sharding-Jdbc版本为2.0.3.用hql语句做简单的查询报错
java.lang.UnsupportedOperationException: Cannot support SQL for `schema.table`
	at io.shardingjdbc.core.parsing.parser.clause.TableReferencesClauseParser.parseTableFactor(TableReferencesClauseParser.java:67)
	at io.shardingjdbc.core.parsing.parser.dialect.oracle.clause.OracleTableReferencesClauseParser.parseQueryTableExpression(OracleTableReferencesClauseParser.java:37)
	at io.shardingjdbc.core.parsing.parser.dialect.oracle.clause.OracleTableReferencesClauseParser.parseTableReference(OracleTableReferencesClauseParser.java:30)
	at io.shardingjdbc.core.parsing.parser.clause.TableReferencesClauseParser.parse(TableReferencesClauseParser.java:54)
	at io.shardingjdbc.core.parsing.parser.sql.dql.select.AbstractSelectParser.parseTable(AbstractSelectParser.java:109)
	at io.shardingjdbc.core.parsing.parser.sql.dql.select.AbstractSelectParser.parseFrom(AbstractSelectParser.java:98)
	at io.shardingjdbc.core.parsing.parser.dialect.oracle.sql.OracleSelectParser.parseInternal(OracleSelectParser.java:53)
	at io.shardingjdbc.core.parsing.parser.sql.dql.select.AbstractSelectParser.parseInternal(AbstractSelectParser.java:81)
	at io.shardingjdbc.core.parsing.parser.sql.dql.select.AbstractSelectParser.parse(AbstractSelectParser.java:68)
	at io.shardingjdbc.core.parsing.parser.sql.dql.select.AbstractSelectParser.parse(AbstractSelectParser.java:46)
	at io.shardingjdbc.core.parsing.SQLParsingEngine.parse(SQLParsingEngine.java:50)
	at io.shardingjdbc.core.routing.router.ParsingSQLRouter.parse(ParsingSQLRouter.java:74)
	at io.shardingjdbc.core.routing.PreparedStatementRoutingEngine.route(PreparedStatementRoutingEngine.java:55)
	at io.shardingjdbc.core.jdbc.core.statement.ShardingPreparedStatement.route(ShardingPreparedStatement.java:150)
	at io.shardingjdbc.core.jdbc.core.statement.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:115)
	at net.sf.hibernate.impl.BatcherImpl.getResultSet(BatcherImpl.java:87)
	at net.sf.hibernate.loader.Loader.getResultSet(Loader.java:875)
	at net.sf.hibernate.loader.Loader.doQuery(Loader.java:269)
	at net.sf.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:133)
	at net.sf.hibernate.loader.Loader.doList(Loader.java:1033)
	at net.sf.hibernate.loader.Loader.list(Loader.java:1024)
	at net.sf.hibernate.hql.QueryTranslator.list(QueryTranslator.java:854)
	at net.sf.hibernate.impl.SessionImpl.find(SessionImpl.java:1544)
	at net.sf.hibernate.impl.QueryImpl.list(QueryImpl.java:39)
	at org.springframework.orm.hibernate.HibernateTemplate$20.doInHibernate(HibernateTemplate.java:722)
	at org.springframework.orm.hibernate.HibernateTemplate.execute(HibernateTemplate.java:367)
	at org.springframework.orm.hibernate.HibernateTemplate.find(HibernateTemplate.java:708)
	at org.springframework.orm.hibernate.HibernateTemplate.find(HibernateTemplate.java:699)

**Comment by terrymanu** [comment]
please do not use schema.table

**Comment by meta-life** [comment]
你好，感谢回复！hql类似 from Model m where m.xx=? ,没使用schema.table

**Comment by meta-life** [comment]
还有个问题，一张表未配置分片规则使用默认的数据源，是否可以跳过sql重写阶段

**Comment by terrymanu** [comment]
@meta-life please provide a demo to reproduce it

**Comment by terrymanu** [comment]
no response for very long time, just close it.
