### ISSUE TITLE
SUM、IFNULL NOT WORKING CORRECTLY WITH SHARDING!

### ISSUE THREAD

**Issue by Mailerm** [sharding-sphere/sharding-sphere#805]
IFNULL/COALESCE(#786)配合SUM关键字 似乎在执行SQL后才会解析最后并没有合并结果，导致了出现第二个BUG。

- Version: 2.0.3
- DB: MySQL 5.6
- Mapper:
````xml
	<select id="statsBy" resultType="java.lang.Integer">
		SELECT IFNULL(SUM(a.`value`), 0) AS 'total_value'
		FROM `_payment_plus` a
		<where>
			a.`park_uuid` = #{park_uuid} AND
			a.`_serial` = #{_serial} AND
            a.`status` = ${@com.chinaroad.persistence.consts.payment.Status@Available} AND
            a.`result` = ${@com.chinaroad.persistence.consts.payment.Result@Success}
            <if test="pay_types != null and pay_types.size() > 0">
                AND a.`pay_type` IN
                <foreach item="item" collection="pay_types" open="(" separator="," close=")">
                    #{item}
                </foreach>
            </if>
		</where>
	</select>
````

## BUG 1:
Execute SQL:
````
SELECT SUM(a.`value`), 0 AS 'total_value'
````

Error:
````
11:56:51.752 INFO  [main] - {dataSource-1} inited
11:56:52.890 INFO  [main] - {dataSource-2} inited
11:56:53.601 INFO  [main] - {dataSource-3} inited
11:56:54.512 INFO  [main] - {dataSource-4} inited
11:57:00.046 INFO  [main] - Started ParkingRecordRepostoryTest in 10.267 seconds (JVM running for 11.599)
11:57:00.189 INFO  [main] - Logic SQL: SELECT SUM(a.`value`) AS 'total_value'
		FROM `_payment_plus` a
		 WHERE a.`park_uuid` = ? AND
			a.`_serial` = ? AND
            a.`status` = 1 AND
            a.`result` = 1
            
                AND a.`pay_type` IN
                (
                    ?
                )
11:57:00.190 INFO  [main] - SQLStatement: SelectStatement(super=DQLStatement(super=AbstractSQLStatement(type=DQL, tables=Tables(tables=[Table(name=__payment_plus, alias=Optional.of(a))]), conditions=Conditions(conditions={}), sqlTokens=[TableToken(beginPosition=46, originalLiterals=`__payment_plus`)], parametersIndex=3)), containStar=false, selectListLastPosition=41, groupByLastPosition=0, items=[AggregationSelectItem(type=SUM, innerExpression=(a.`value`), alias=Optional.of(total_value), derivedAggregationSelectItems=[], index=-1)], groupByItems=[], orderByItems=[], limit=null, subQueryStatement=null)
11:57:00.190 INFO  [main] - Actual SQL: _default ::: SELECT SUM(a.`value`) AS 'total_value'
		FROM _payment a
		 WHERE a.`park_uuid` = ? AND
			a.`_serial` = ? AND
            a.`status` = 1 AND
            a.`result` = 1
            
                AND a.`pay_type` IN
                (
                    ?
                ) ::: [5f3ce246-484b-4dbf-a712-cffa65614100, 2018050709334165532699392, 2]
11:57:00.190 INFO  [main] - Actual SQL: _2018 ::: SELECT SUM(a.`value`) AS 'total_value'
		FROM __payment a
		 WHERE a.`park_uuid` = ? AND
			a.`_serial` = ? AND
            a.`status` = 1 AND
            a.`result` = 1
            
                AND a.`pay_type` IN
                (
                    ?
                ) ::: [5f3ce246-484b-4dbf-a712-cffa65614100, 2018050709334165532699392, 2]
11:57:00.190 INFO  [main] - Actual SQL: _2019 ::: SELECT SUM(a.`value`) AS 'total_value'
		FROM __payment a
		 WHERE a.`park_uuid` = ? AND
			a.`_serial` = ? AND
            a.`status` = 1 AND
            a.`result` = 1
            
                AND a.`pay_type` IN
                (
                    ?
                ) ::: [5f3ce246-484b-4dbf-a712-cffa65614100, 2018050709334165532699392, 2]

org.apache.ibatis.binding.BindingException: Mapper method 'com.chinaroad.persistence.mapper..ParkingPaymentRepository.statsBy attempted to return null from a method with a primitive return type (int).

````

## BUG 2:
Execute SQL:
````
SELECT IFNULL(SUM(a.`value`), 0) AS 'total_value'
````
Error:
````
11:50:40.837 INFO  [main] - {dataSource-1} inited
11:50:41.882 INFO  [main] - {dataSource-2} inited
11:50:42.639 INFO  [main] - {dataSource-3} inited
11:50:43.529 INFO  [main] - {dataSource-4} inited
11:50:53.465 INFO  [main] - Started ParkingRecordRepostoryTest in 14.366 seconds (JVM running for 15.805)
11:50:53.618 INFO  [main] - Logic SQL: SELECT IFNULL(SUM(a.`value`), 0) AS 'total_value'
		FROM `__payment_plus` a
		 WHERE a.`park_uuid` = ? AND
			a.`_serial` = ? AND
            a.`status` = 1 AND
            a.`result` = 1
            
                AND a.`pay_type` IN
                (
                    ?
                )
11:50:53.619 INFO  [main] - SQLStatement: SelectStatement(super=DQLStatement(super=AbstractSQLStatement(type=DQL, tables=Tables(tables=[Table(name=__payment_plus, alias=Optional.of(a))]), conditions=Conditions(conditions={}), sqlTokens=[TableToken(beginPosition=57, originalLiterals=`__payment_plus`)], parametersIndex=3)), containStar=false, selectListLastPosition=52, groupByLastPosition=0, items=[CommonSelectItem(expression=IFNULL(SUM(a.value), 0), alias=Optional.of(total_value))], groupByItems=[], orderByItems=[], limit=null, subQueryStatement=null)
11:50:53.620 INFO  [main] - Actual SQL: _default ::: SELECT IFNULL(SUM(a.`value`), 0) AS 'total_value'
		FROM __payment a
		 WHERE a.`park_uuid` = ? AND
			a.`_serial` = ? AND
            a.`status` = 1 AND
            a.`result` = 1
            
                AND a.`pay_type` IN
                (
                    ?
                ) ::: [5f3ce246-484b-4dbf-a712-cffa65614100, 201805070933416553269939, 2]
11:50:53.620 INFO  [main] - Actual SQL: _2018 ::: SELECT IFNULL(SUM(a.`value`), 0) AS 'total_value'
		FROM __payment a
		 WHERE a.`park_uuid` = ? AND
			a.`_serial` = ? AND
            a.`status` = 1 AND
            a.`result` = 1
            
                AND a.`pay_type` IN
                (
                    ?
                ) ::: [5f3ce246-484b-4dbf-a712-cffa65614100, 201805070933416553269939, 2]
11:50:53.620 INFO  [main] - Actual SQL: _2019 ::: SELECT IFNULL(SUM(a.`value`), 0) AS 'total_value'
		FROM __payment a
		 WHERE a.`park_uuid` = ? AND
			a.`_serial` = ? AND
            a.`status` = 1 AND
            a.`result` = 1
            
                AND a.`pay_type` IN
                (
                    ?
                ) ::: [5f3ce246-484b-4dbf-a712-cffa65614100, 201805070933416553269939, 2]

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 3

	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy64.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:82)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy73.statsByParking(Unknown Source)
	at com.chinaroad..persistence.mapper.ParkingRecordRepostoryTest.overdraft(ParkingRecordRepostoryTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 3
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 34 more
````

**Comment by imrobin** [comment]
我也出现同样问题.
Version:2.0.3
Mysql:5.7.21

**Comment by terrymanu** [comment]
no plan to support aggregation nested sql for now

**Comment by Anricx** [comment]
4.x support now?

**Comment by changchangjie** [comment]
+1

**Comment by yanglangfei** [comment]
+1

**Comment by 2241101100** [comment]
+1
