### ISSUE TITLE
spring-jpa oracle数据源使用报错，java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

### ISSUE THREAD

**Issue by jiashuaizhang** [sharding-sphere/sharding-sphere#877]
如题，按照官网的例子springboot-jpa搭建，版本号3.0.0.M1，连接池我用的druid1.0.12,使用mysql数据库功能正常。
切换oracle数据源后，就找不到表了。打印sql看到分表是正确的，不清楚是不是表空间的问题。
萌新想请教下，这个是我哪里弄错了呢
`
java.sql.SQLSyntaxErrorException: ORA-00942: 表或视图不存在

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:440) ~[ojdbc6-11.2.0.jar:11.2.0.2.0]
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396) ~[ojdbc6-11.2.0.jar:11.2.0.2.0]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:837) ~[ojdbc6-11.2.0.jar:11.2.0.2.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:445) ~[ojdbc6-11.2.0.jar:11.2.0.2.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:191) ~[ojdbc6-11.2.0.jar:11.2.0.2.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:523) ~[ojdbc6-11.2.0.jar:11.2.0.2.0]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207) ~[ojdbc6-11.2.0.jar:11.2.0.2.0]
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:863) ~[ojdbc6-11.2.0.jar:11.2.0.2.0]
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1153) ~[ojdbc6-11.2.0.jar:11.2.0.2.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1275) ~[ojdbc6-11.2.0.jar:11.2.0.2.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3576) ~[ojdbc6-11.2.0.jar:11.2.0.2.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3620) ~[ojdbc6-11.2.0.jar:11.2.0.2.0]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1491) ~[ojdbc6-11.2.0.jar:11.2.0.2.0]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227) ~[druid-1.0.12.jar:1.0.12]
	at io.shardingsphere.core.executor.type.prepared.PreparedStatementExecutor$1.execute(PreparedStatementExecutor.java:59) ~[sharding-jdbc-3.0.0.M1.jar:na]
	at io.shardingsphere.core.executor.type.prepared.PreparedStatementExecutor$1.execute(PreparedStatementExecutor.java:55) ~[sharding-jdbc-3.0.0.M1.jar:na]
	at io.shardingsphere.core.executor.ExecutorEngine.executeInternal(ExecutorEngine.java:147) ~[sharding-jdbc-3.0.0.M1.jar:na]
	at io.shardingsphere.core.executor.ExecutorEngine.access$000(ExecutorEngine.java:58) ~[sharding-jdbc-3.0.0.M1.jar:na]
	at io.shardingsphere.core.executor.ExecutorEngine$1.call(ExecutorEngine.java:122) ~[sharding-jdbc-3.0.0.M1.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]`

**Comment by terrymanu** [comment]
just create your table on oracle

**Comment by jiashuaizhang** [comment]
我当然建了表了啊，这明显是个问题啊。
从mysql切换到oracle，切换数据库地址和驱动，就不需要别的改动了吧。
然后出现了这个诡异的问题，如果各位大神有思路，还请耐心多给小弟打几个字。

**Comment by jiashuaizhang** [comment]
我以为是自己犯了什么stupid mistake，错误原因不明确，我只能先放一放，后续再尝试单独测试数据源或重建表，再不行就得撸源码了😂Thanks anyway

**Comment by fdlzp** [comment]
how to deal with it?
也是mysql可以，改了驱动和url还有方言，然后就有错，暂时定位不到具体原因


[WARN ] 2019-03-26 10:16:49,625 --main-- [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [io/shardingjdbc/spring/boot/SpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (The Network Adapter could not establish the connection) 
[INFO ] 2019-03-26 10:16:49,627 --main-- [org.apache.catalina.core.StandardService] Stopping service [Tomcat] 
[ERROR] 2019-03-26 10:16:49,650 --main-- [org.springframework.boot.SpringApplication] Application startup failed 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [io/shardingjdbc/spring/boot/SpringBootConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (The Network Adapter could not establish the connection)

**Comment by fdlzp** [comment]
可以给个结合oracle的简单demo吗
784423812@qq.com
感激不尽
