### ISSUE TITLE
spring配置的方式使用$->貌似解析不了

### ISSUE THREAD

**Issue by visoeclipse** [sharding-sphere/sharding-sphere#882]
最新的2.0.3

配置：
<sharding:table-rules>
                <sharding:table-rule logic-table="user" actual-data-nodes='dataSource.user_$->{0..99}' database-strategy-ref="noneStrategy" table-strategy-ref="userTableStrategy"/>
            </sharding:table-rules>

使用$->貌似解析不了，

出现如下错误：

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.shardingjdbc.spring.datasource.SpringShardingDataSource]: Constructor threw exception; nested exception is org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 1: illegal string body character after dollar sign;
   solution: either escape a literal dollar sign "\$5" or bracket the value expression "${5}" @ line 1, column 19.
   "dataSource.user_$->{0..99}"
                                 ^
1 error

	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:182)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
	... 41 more
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 1: illegal string body character after dollar sign;
   solution: either escape a literal dollar sign "\$5" or bracket the value expression "${5}" @ line 1, column 19.
   "dataSource.user_$->{0..99}"
                                 ^

**Comment by terrymanu** [comment]
please read release notes, to make sure features are released at that version
