### ISSUE TITLE
shardingjdbc for update 之后update事务死锁问题

### ISSUE THREAD

**Issue by afredlyj** [sharding-sphere/sharding-sphere#906]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
shardingjdbc 1.5.4.1 和2.0.0.M3
下面的测试结果是基于 1.5.4.1。

### Expected behavior （您预期的结果是）
事务执行成功返回

### Actual behavior （实际运行的结果是）
同一个事务下，`select ... for update`成功返回之后，`update` 语句获取锁超时回滚

### Steps to reproduce the behavior （可重现问题的操作步骤）

业务代码:
```java

public class App 
{
    public static void main( String[] args )
    {
        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("sharding.xml");
        TransactionalManager manager = context.getBean(TransactionalManager.class);
        manager.test();

        System.out.println("运行结束");
    }
}

  package afred.javademo;

import afred.javademo.dao.domain.StudentDO;
import afred.javademo.dao.domain.StudentDOExample;
import afred.javademo.dao.mapper.StudentDOMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

public class TransactionalManager {

    @Autowired
    private StudentDOMapper mapper;

    @Transactional(rollbackFor = Exception.class)
    public void test() {
        StudentDOExample studentDOExample = new StudentDOExample();
        studentDOExample.createCriteria().andIdEqualTo(1);
        int i = mapper.countByExample(studentDOExample);
        System.out.println("查询结果 : " + i);

        StudentDO student = new StudentDO();
        student.setId(1);
        student.setAge(18);
        student.setName("afreddd");
//        mapper.insert(student);

        StudentDOExample example = new StudentDOExample();
        example.createCriteria().andIdEqualTo(1);
        System.out.println("查询结果 : " + mapper.selectForUpdateByExample(example));

        student.setName("hello");
        mapper.updateByExample(student, example);
    }
}

```

mapper配置
```java
  <select id="selectForUpdateByExample" resultMap="BaseResultMap" parameterType="afred.javademo.dao.domain.StudentDOExample" >
    select
    <if test="distinct" >
      distinct
    </if>
    'true' as QUERYID,
    <include refid="Base_Column_List" />
    from student
    <if test="_parameter != null" >
      <include refid="Example_Where_Clause" />
    </if>
    <if test="orderByClause != null" >
      order by ${orderByClause}
    </if>
    for update
  </select>
```

Spring事务配置
```java
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.springframework.org/schema/beans" xmlns:context="http://www.springframework.org/schema/context" xmlns:mybatis="http://mybatis.org/schema/mybatis-spring"
  xmlns:tx="http://www.springframework.org/schema/tx" xmlns:aop="http://www.springframework.org/schema/aop" xmlns:rdb="http://www.dangdang.com/schema/ddframe/rdb"
  xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
	http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd
	http://mybatis.org/schema/mybatis-spring http://mybatis.org/schema/mybatis-spring.xsd
	http://www.springframework.org/schema/tx  http://www.springframework.org/schema/tx/spring-tx.xsd
    http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop.xsd
    http://www.dangdang.com/schema/ddframe/rdb http://www.dangdang.com/schema/ddframe/rdb/rdb.xsd">

    <tx:annotation-driven proxy-target-class="true"
                          transaction-manager="mysqltransactionManager" />

    <bean id="mysqltransactionManager"
          class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
        <property name="dataSource" ref="shardingDataSource" />
    </bean>

    <bean id="db" class="com.alibaba.druid.pool.DruidDataSource" init-method="init" destroy-method="close">
        <property name="driverClassName" value="com.mysql.jdbc.Driver" />
        <property name="url" value="jdbc:mysql://xxxxxx:33066/test" />
        <property name="username" value="xxxxxxx" />
        <property name="password" value="xxxxx" />
        <property name="initialSize" value="10" />
        <property name="minIdle" value="10" />
        <property name="maxActive" value="10" />
        <property name="maxWait" value="10000" />
        <property name="validationQuery" value="SELECT 1" />
        <property name="testOnBorrow" value="true" />
    </bean>

    <!-- 配置主从读写分离 -->
    <rdb:master-slave-data-source id="db_credits_0" master-data-source-ref="db" slave-data-sources-ref="db" />

	<!-- 虚拟数据源 -->
	<rdb:data-source id="shardingDataSource">
		<rdb:sharding-rule data-sources="db_credits_0" default-data-source="db_credits_0">
			<!-- 定义逻辑表和路由策略 -->
			<rdb:table-rules>
				<rdb:table-rule logic-table="student"/>
            </rdb:table-rules>
			<!-- 分库路由 -->
			<rdb:default-database-strategy sharding-columns="none" algorithm-class="com.dangdang.ddframe.rdb.sharding.api.strategy.database.NoneDatabaseShardingAlgorithm" />
		</rdb:sharding-rule>
	</rdb:data-source>

    <bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
        <property name="dataSource" ref="shardingDataSource" />
        <property name="mapperLocations">
            <list>
                <value>classpath:META-INFO/mybatis/mapper/*Mapper.xml</value>
            </list>
        </property>
    </bean>

    <bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
        <property name="basePackage" value="afred.javademo.dao" />
        <property name="sqlSessionFactoryBeanName" value="sqlSessionFactory"></property>
    </bean>

  <bean id="manager" class="afred.javademo.TransactionalManager"/>


</beans>
```

程序日志:

```java
### The error may involve afred.javademo.dao.mapper.StudentDOMapper.selectForUpdateByExample-Inline
### The error occurred while setting parameters
### SQL: select           'true' as QUERYID,           id, name, age         from student                    WHERE (  id = ? )                      for update
### Cause: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: java.sql.SQLException: Lock wait timeout exceeded; try restarting transaction
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:107)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:354)
	... 18 more
Caused by: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: java.sql.SQLException: Lock wait timeout exceeded; try restarting transaction
	at com.dangdang.ddframe.rdb.sharding.executor.ExecutorExceptionHandler.handleException(ExecutorExceptionHandler.java:61)
	at com.dangdang.ddframe.rdb.sharding.executor.PreparedStatementExecutor.executeInternal(PreparedStatementExecutor.java:195)
	at com.dangdang.ddframe.rdb.sharding.executor.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:169)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:55)
	at $Proxy11.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:56)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:70)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:57)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:259)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:132)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:105)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:81)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:104)
	... 24 more
Caused by: java.sql.SQLException: Lock wait timeout exceeded; try restarting transaction
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1203)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
	at com.dangdang.ddframe.rdb.sharding.executor.PreparedStatementExecutor.executeInternal(PreparedStatementExecutor.java:192)
	... 40 more
```

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by afredlyj** [comment]
版本 1.4.2 正常，1.5.4.1和2.0.0.M3 异常

**Comment by afredlyj** [comment]
原因和`https://github.com/sharding-sphere/sharding-sphere/issues/899`一样，配置了读写分离，for update 路由到从库，导致后续的update获取锁超时，暂时用`HintManager`强制走主库。
