### ISSUE TITLE
spring boot sharding-jdbc初始化失败

### ISSUE THREAD

**Issue by An0nymous0** [sharding-sphere/sharding-sphere#994]
看了下源码应该是初始化时反射的名称对不上。 所以导致jdbc url无法赋值,如果把官网例子中的url改成jdbcUrl才可以跑起来。只不过没详细看源代码。不知道这个定义的名称除了反射给HikariConfig中还有没有其他地方用到了。
![image](https://user-images.githubusercontent.com/6836030/42504172-71f4540a-846d-11e8-8814-24a9b6ac8976.png)
![image](https://user-images.githubusercontent.com/6836030/42504363-1e430d6e-846e-11e8-9513-d7afe7ad83db.png)
![image](https://user-images.githubusercontent.com/6836030/42504232-ab5a2512-846d-11e8-84e7-1eec90243c14.png)

配置
sharding:
  jdbc:
    datasource:
      names: ds_master,ds_slave0,ds_slave1
      ds_master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yhbj_main?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password:
      ds_slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yhbj_main?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password:
      ds_slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yhbj_main?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password:
    config:
      masterslave:
        name: ds_ms
        master-data-source-name: ds_master
        slave-data-source-names: ds_slave0,ds_slave1

最后报错
Caused by: java.lang.IllegalArgumentException: jdbcUrl is required with driverClassName.
	at com.zaxxer.hikari.HikariConfig.validate(HikariConfig.java:893)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:94)
	at io.shardingsphere.core.jdbc.adapter.AbstractDataSourceAdapter.getDatabaseType(AbstractDataSourceAdapter.java:62)
	at io.shardingsphere.core.jdbc.adapter.AbstractDataSourceAdapter.getDatabaseType(AbstractDataSourceAdapter.java:51)
	at io.shardingsphere.core.jdbc.adapter.AbstractDataSourceAdapter.<init>(AbstractDataSourceAdapter.java:45)
	at io.shardingsphere.core.jdbc.core.datasource.MasterSlaveDataSource.<init>(MasterSlaveDataSource.java:47)
	at io.shardingsphere.core.api.MasterSlaveDataSourceFactory.createDataSource(MasterSlaveDataSourceFactory.java:48)
	at io.shardingsphere.jdbc.spring.boot.SpringBootConfiguration.dataSource(SpringBootConfiguration.java:67)
	at io.shardingsphere.jdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$e6e9c19a.CGLIB$dataSource$1(<generated>)
	at io.shardingsphere.jdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$e6e9c19a$$FastClassBySpringCGLIB$$f6857956.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at io.shardingsphere.jdbc.spring.boot.SpringBootConfiguration$$EnhancerBySpringCGLIB$$e6e9c19a.dataSource(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)

**Comment by terrymanu** [comment]
Hello, we prefer use english to discuss issue.
For bug report, we can keep it, but for question, we will close directly.

**Comment by fddOs** [comment]
@An0nymous0 我也发现了这个问题，HiKariDataSource继承了HiKariConfig 源码中的dataSource.getClass().getMethod()改成dataSource.getClass().getSuperClass().getMethod()就没问题了，官方文档还有很多错误的配置示例，简直了

**Comment by changelzj** [comment]
> @An0nymous0 用spring.shardingsphere.datasource.{datasourcename}.jdbcUrl=xxx 就可以了

亲测可行！应该就是每个数据源必须使用各自对URL的变量命名

**Comment by changelzj** [comment]
> @An0nymous0 用spring.shardingsphere.datasource.{datasourcename}.jdbcUrl=xxx 就可以了

亲测可行！应该就是每个数据源必须使用各自对URL的变量命名
